### ISSUE TITLE
Bring back the Realm cache

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-object-store#1067]
Pre-Core6, we had a per-thread Realm cache in OS. This is gone now, but seems valuable as most SDKs have some sort of caching in place. To avoid duplicating that logic (and to make it easier for .NET to migrate to Core6), let's bring back the OS cache and add an SDK task to eventually deprecate their bespoke caching solutions in favor of the common one.

**Comment by fealebenpae** [comment]
Closing in favor of #1069
