### ISSUE TITLE
Consolidate user logout mechanics

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-object-store#1095]
Currently, we have `app::remove_user` which invalidates the user's token and `user::log_out` which is a local operation only. We should change `user::log_out` to also call the server and attempt to invalidate the token, but even better, we should probably consolidate both of these methods in a single call that accepts a boolean `remove_local_data` parameter. Since it needs the transport factory to perform the request, we should probably consolidate around `app::remove_user(bool remove_local_data)`.

Note that this may or may not be an accurate reflection of the public API, but this is fine and we don't have to bikeshed on it.

**Comment by leemaguire** [comment]
`app::log_out` currently calls the server in attempt to invalidate the token. The token will be removed and the user will be marked as logged out whether the server call succeeds or not.

**Comment by nirinchev** [comment]
That's my point though - `user::log_out` should also call the server and invalidate the token.

**Comment by jsflax** [comment]
I think this is mostly a misnomer due to the criss cross integration that the SDKs did once most functions were moved to `User`.

**Comment by bmunkholm** [comment]
Moved to https://github.com/realm/realm-core/issues/4184
