### ISSUE TITLE
Allow creating a user automatically with Credentials.UsernamePassword

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-object-store#1096]
This tripped me up when writing tests for the login functionality and I imagine it'll confuse others as well. Currently, trying to register a user via `app.Login(Credentials.UsernamePassword)` will fail with 401 and no further information, which means the developer will have to go in the server UI, open the logs, see the error log with content `invalid username` and guess that this is caused because `app.Login` only logs the user, but doesn't attempt to create them. This is inconsistent with other credential types as those will create non-existent users (e.g. facebook, google, anonymous).

While I do realize there's value in enforcing that new users aren't created via `app.Login` (e.g. fat-fingering a username shouldn't create a new user for you), there's also value in being flexible. That's why I would suggest adding a 3rd optional argument to `Credentials.UsernamePassword` that will be `bool createUser`, which will default to `false`. That way, we use the API itself as a guide for developers that points out that registering and logging in a user are two separate things, while also reducing friction in the beginning.

**Comment by jsflax** [comment]
You want users to be given a dummy `SyncUser` on registration?

**Comment by nirinchev** [comment]
No, I would rather have the Login call be implemented like:

```
auto response = do_request("login", args);

if (response.status_code == 401 && provider == "username" && create_user) {
    var registerResponse = app->provider_client<UsernamePassword>().register_user(args);
    if (registerResponse.status_code = 204) {
        response = do_request("login", args);
    }
}
```

Essentially, special-casing username-password to invoke the register method if the credentials were created with `create_user: true` and the login response is 401, then retry the login.

**Comment by leemaguire** [comment]
This sounds like it's more valuable for our tests than actual real world usage. I would imagine there would be a lot of fat finger mistakes made (and of course its the developers discretion to use this solution), but also this will bloat the log_in code which doesn't feel right.

**Comment by nirinchev** [comment]
My concern is that this makes the email/password credentials behave differently from the other credential types which will create a user the first time they're used. That being said, I agree that i's probably not a common real-world use case.

**Comment by fealebenpae** [comment]
@nirinchev should we close this?

**Comment by nirinchev** [comment]
I'm still a bit split on it - I don't feel the current API is very intuitive, but also don't have great ideas about how it can be improved.

**Comment by nirinchev** [comment]
A user has requested this on forums: https://developer.mongodb.com/community/forums/t/auto-create-email-password-users/99018

**Comment by bmunkholm** [comment]
Moved to https://github.com/realm/realm-core/issues/4606
