### ISSUE TITLE
Rename/clarify app config parameters for platform and SDK

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-object-store#1100]
Currently, we have 3 app config parameters related to SDK and platform and their versions:

- `platform` actually contains information about the SDK, e.g. `Realm Cocoa`. This should probably be renamed to `sdk`.
- `platform_version` contains the version of the operating system but doesn't contain the name of the OS itself. We should either introduce a `platform` config parameter for the OS name or combine the name and the version in one parameter.
- `sdk_version` contains the version of the SDK and seems to be fine.

**Comment by cmelchior** [comment]
This probably has to be aligned with how this is being used on the server. As this seems a bit inconsistent.

This is the current behavior:

![image](https://user-images.githubusercontent.com/406066/94244887-ce61c280-ff19-11ea-9bce-eee742df7ccc.png)

But the docs claim the OS version is also present (which it is not):

![image](https://user-images.githubusercontent.com/406066/94245242-4203cf80-ff1a-11ea-9292-d79ca2c01a7a.png)

Ideally, I would like to be able to send "platform", "platform OS version", "device type", "sdk type" and "sdk
 version"

**Comment by nirinchev** [comment]
I don't see a huge benefit of having the versions separate from the things they are describing. It's not like users can query for all requests made by SDK X or clients on platform Y. And even if they could, they could just do a sort of `SDK startsWith 'Realm Cocoa'`. So we can probably have just `sdk` and `platform`, which will include the name + version. For device type, I agree it would be nice, but it would require server-side changes to accommodate that and can be iteratively added after GA.

**Comment by bmunkholm** [comment]
Moved to https://github.com/realm/realm-core/issues/4183
