### ISSUE TITLE
Fix lossy conversion for Bson Doubles and Bson MongoTimestamps

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-object-store#1106]
It seems like large numbers fail to roundtrip deserialization+serialization. Notably, `{ "$numberDouble": "1.7976931348623157E+308" }` gets converted correctly to a bson value, but when I try to serialize it back to string, I get `{"$numberDouble":"1.79769e+308"}`.

**Comment by jsflax** [comment]
This is known, the tests for this are intentionally tagged as "lossy". I would consider renaming this ticket to `Fix lossy conversion for Bson Doubles and Bson MongoTimestamps`.

**Comment by nirinchev** [comment]
Ah, cool - I did a quick GitHub issue search, but didn't think of looking at the tests. Will rename tomorrow.
