### ISSUE TITLE
Expose API for calling functions with already serialized arguments

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-object-store#1107]
Since .NET can't really pass a bson array from managed to native, we serialize it to string, then deserialize it in the C layer, only for OS to then serialize it again. It would be nice if OS exposed an API to call a function with pre-serialized string as opposed to a bson array. Similarly, it would be nice if the callback of this API used a string instead of the bson type.

**Comment by bmunkholm** [comment]
Moved to https://github.com/realm/realm-core/issues/4182
