### ISSUE TITLE
RemoteMongoClient should expose API that accepts a user

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-object-store#1109]
Currently, the RemoteMongoClient only operates on the current app user, but the SDK exposes the API on the `User` object, which could introduce subtle security bugs where the user calling `collection.Find()` doesn't have permissions for a particular document, but the current user does.

**Comment by jbreams** [comment]
Do you intend for every method on RemoteMongoCollection to take a user parameter, or can the RemoteMongoClient factory method take a user parameter and RemoteMongoClient/Database/Collection will be bound to that user?

**Comment by jsflax** [comment]
The cleanest way to do this would be to have the ObjectStore mirror the SDKs– we should move the RemoteMongoXs under the `User` class as they are in the SDKs. The `User` (in the OS) should start taking an `AuthRequestClient` parameter that it uses to make these network calls.

**Comment by jsflax** [comment]
However the path of least resistance would be to have the RemoteMongoClient bound to a user.
