### ISSUE TITLE
Access token is not refreshed when user uses the http API

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-object-store#1119]
I encountered this in a .NET Core app - I logged in an anonymous user, then a few days later, I tried running the app again. When trying to use the remote mongo API, I get `invalid session`. When I inspected the user object, the access token had expired more than 5 days ago. So I see two orthogonal problems exposed by this:
1. When calling `app.LoginAsync` with anonymous credentials, we should probably attempt to refresh the access token before returning a cached user.
2. When calling any of the http methods, we should refresh the access token if it has expired.

**Comment by jsflax** [comment]
We have logic that ensures that tokens are auto refreshed, so you've likely uncovered a bug here.

**Comment by nirinchev** [comment]
I briefly reviewed the code and may be missing something, but the way I read it, in `App::handle_auth_failure`, we only handle http errors:

https://github.com/realm/realm-object-store/blob/6b44209e6fcac0137e193c96444f93c50d184d06/src/sync/app.cpp#L981

But in `check_for_errors`, we will return `service_error` if the content type is application/json:

https://github.com/realm/realm-object-store/blob/6b44209e6fcac0137e193c96444f93c50d184d06/src/sync/app_utils.hpp#L49-L64

This means that if the server responds with 401, but `application/json` content, we're constructing a service error which then circumvents the 401 check and prevents the token refresh.

**Comment by nirinchev** [comment]
@leemaguire I vaguely remember you working on the token refresh code - can you confirm if my understanding is correct or if I'm missing some piece of the puzzle?

**Comment by leemaguire** [comment]
@nirinchev Your understanding is correct. This does look like a bug. `static util::Optional<AppError> check_for_errors(const Response& response)` likely needs a rework because if something does have `application/json` as a header, it will try parse an error message from the body and http status code.

**Comment by nirinchev** [comment]
Fixed by https://github.com/realm/realm-object-store/pull/1124
