### ISSUE TITLE
Align client reset error codes

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-object-store#1121]
In sync_session.cpp we have 11 error codes that will mark the file for deletion:

https://github.com/realm/realm-object-store/blob/6b44209e6fcac0137e193c96444f93c50d184d06/src/sync/sync_session.cpp#L463-L473

But in sync_config.hpp we only have 6 error codes that return `true` for `is_client_reset_requested`:

https://github.com/realm/realm-object-store/blob/6b44209e6fcac0137e193c96444f93c50d184d06/src/sync/sync_config.hpp#L105-L110

We should make sure these are equivalent.

**Comment by nirinchev** [comment]
There appear to be a bunch of other error codes that should probably be considered client reset ones, but they're not in either of these lists.

We should ping the sync team for an up-to-date list of client reset codes.

**Comment by bmunkholm** [comment]
Moved to https://github.com/realm/realm-core/issues/4181
