### ISSUE TITLE
SyncUserProfile should hold a map of unknown fields

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-object-store#1123]
Currently we're only reading the known fields from `profile_data`:

https://github.com/realm/realm-object-store/blob/6b44209e6fcac0137e193c96444f93c50d184d06/src/sync/app.cpp#L619-L627

Instead, we should have a map of unknown fields because those may be valuable for end users. When a user configured the [metadata fields](https://docs.mongodb.com/realm/authentication/custom-jwt/#metadata-fields) for JWT auth, those get sent in the profileresponse.data field.

This is related to (https://github.com/realm/realm-js/pull/3302) that addresses it for Realm Web, but we need it fixed for other SDKs as well.

**Comment by bmunkholm** [comment]
Moved to https://github.com/realm/realm-core/issues/4131
