### ISSUE TITLE
Need info about realm-object-store w/ core 10.x 

### ISSUE THREAD

**Issue by deleeuwict** [realm/realm-object-store#1130]
Hello,

I have a bunch of C++ 11 projects that directly link with realm-object-store.lib. At the moment the realm core version in use is 6.x  (according to the dependencies.list file), but I noticed that a new major core 10.x is being developed and will (I assume) be integrated with realm-object-store soon.

As I have absolutely no idea what exactly the technical difference with 10.x is, I have only 2 general questions:

1. If one would recompile the upcoming realm-object-store release for 10.x,  will existing realm-object-store code break or would it work without any changes?

2. Where can one read more about the exact differences between 6,x / 10.x ?

Thanks.

GertJan.

PS. writing this question because of pull request https://github.com/realm/realm-object-store/pull/1126

**Comment by fealebenpae** [comment]
Hey @deleeuwict,

The v10 release line of Realm Core and SDKs is a major upgrade that adds support for new data types and replaces the legacy Realm Object Store synchronization backend with MongoDB Realm.

The Object Store that works with Core 6 will not work with Core 10. As Object Store is what we consider an internal component of the Realm SDKs, we don't provide the same compatibility guarantees as we do in the SDK public API. This means that the Object Store API is internal, and will break between releases. Any given "snapshot" of Object Store is only compatible with the Core release described in `dependencies.list`. While it is of course possible to use it in your projects directly, we don't do proper releases of Object Store with changelogs and semantic versioning, which might make it hard to keep up with the component's development.

That said, unless your projects need the new data types introduced in v10 then it's probably safe to stick to using the `core-6` branch. It will still receive security and bug fixes for as long as the legacy Realm Cloud is operational.

Out of curiosity, what use do you have for Object Store directly that cannot be satisfied by one of the SDKs?

**Comment by deleeuwict** [comment]
@fealebenpae Thank you so much for your helpful answer!  

To be honest, as of yet I am not familair with the official Realm SDKs, about a year ago I have started up development with Realm and haven taken as base the source-code of the Realm & object-store unit tests. I am greatly impressed by the performance of Realm and I guess that is the reason why I am find myself at the low-level end of things at the moment :-) .   

Since you mentioned that the 6.x branch will still be updated, I suppose that for the moment I will stick with this version.
