### ISSUE TITLE
Single thread for all Realm's external commit helper

### ISSUE THREAD

**Issue by beeender** [realm/realm-object-store#152]
Currently every Realm config needs a thread for external commit helper. This is a resource wasting for users who have more than one Realm in the app. (We have users have 20+ Realms in one app, so it is not a ideal situation for them.)

This becomes an issue for realm-java after https://github.com/realm/realm-java/pull/3370 merged.

**Comment by bdash** [comment]
What resources are you concerned about? The commit helper thread spends most of its life idle, consuming only the small amount of memory used by its stack.

**Comment by diegomontoya** [comment]
@bdash 

1. Each android thread consumes 1024kb stack by default. Pretty sure the 1024kb size must be continuous block, not fragmented memory. Android 4 is really slow to recover/defrag memory so you would get oom even if you have 500mb ram left over on the device.
2. Issue 1 is multiplied in new commit when Realm is constantly opened and closed which cause new monitor thread create/destroy thrashing.

**Comment by bdash** [comment]
Is it address space that's the constrained resource, or physical memory? I'd expect that if threads default to a 1MB stack, that would require 1MB of address space with only a fraction of that backed by physical memory for the portion of the stack that is used.

**Comment by beeender** [comment]
Address space consumption is a problem to us as well. Since we need continuous vm space to do mmap.

**Comment by diegomontoya** [comment]
@bdash the 1024KB stack is vm address and not physical memory. At least based on the following wildly inconsistent test results. Check out the crazy low values for Huawei. Both the 2xhuawei and Samsung s6 are running 6.0.1 yet yield totally different values and slightly different error messages.

What really worries is how the Huaweis, with latest os updates, can have such small value. Did Huawei tweak the vm limits in their custom roms? Something to watch out for.

1) On both Huwei Mate8, 4G, 2.2G free ( (Android 6.0.1)) and Huawei P8, 4G, 2.2G free (Android 6.0.1) I can continue to spawn and run 475 simultaneous threads before:

```
W/libc: pthread_create failed: clone failed: Out of memory
W/art: Throwing OutOfMemoryError "pthread_create (1040KB stack) failed: Out of memory"
```

2)  Samsung S6 6.0.1, 3G, 1.3G free  (Android 6.0.1) the same test can create/run 2400 threads. 

``` 
W/libc: pthread_create failed: couldn't allocate 1069056-bytes mapped space: Out of memory
W/art: Throwing OutOfMemoryError "pthread_create (1040KB stack) failed: Try again
``` 

3)  Samsung SMG318 4.2.2 1G, 190MB free (Android 4.2.2) the same test can create/run 1500 threads before crash. 

```
Thread creation failed (err=Invalid argument)
W/System.err: java.lang.OutOfMemoryError: thread creation failed
```

**Comment by bdash** [comment]
@diegomontoya, thanks very much for providing those data points. The results are surprising, and do suggest optimizing this aspect of our design is important for Android.
