### ISSUE TITLE
Move Mac, Android build to the pipeline job

### ISSUE THREAD

**Issue by alebsack** [realm/realm-object-store#199]
We now have linux builds running with a Jenkinsfile.  This means we can now port the mac build to the Jenkinsfile and run all supported platforms with one pipeline.

@fealebenpae @ironage 

Related to #194

**Comment by bdash** [comment]
Looks like the Mac side was taken care of in #212.

**Comment by bdash** [comment]
@alebsack / @emanuelez, is adding an Android CI job something that you'd be able to tackle? Even just testing compilation for the supported architectures would be a good first step. We also have #208 tracking running the unit tests on devices.

**Comment by alebsack** [comment]
@bdash Yeah, I have a WIP PR here: #221
