### ISSUE TITLE
Need reset method for metadata realm/global state for testing

### ISSUE THREAD

**Issue by alazier** [realm/realm-object-store#207]
It isn't currently possible to easily test this functionality in the JS binding.

**Comment by jpsim** [comment]
Should go in [`SyncManager::reset_for_testing()`](https://github.com/realm/realm-object-store/blob/b597945d068856a7b7a5bb8e5d68d6403ab87961/src/sync/sync_manager.hpp#L105-L106). Note that some metadata is already being reset in there (e.g. users). Could you be more explicit about what else you'd like to see reset?

**Comment by alazier** [comment]
That seems to be what I should be calling but I get a segfault when calling it.

**Comment by jpsim** [comment]
Perhaps you could take a look at the existing usage in the object store tests to find out if you're using it differently?

* [tests/sync/session.cpp](https://github.com/realm/realm-object-store/blob/b597945d068856a7b7a5bb8e5d68d6403ab87961/tests/sync/session.cpp#L121)
* [tests/sync/user.cpp](https://github.com/realm/realm-object-store/blob/b597945d068856a7b7a5bb8e5d68d6403ab87961/tests/sync/user.cpp#L33)
* [tests/sync/sync_manager.cpp](https://github.com/realm/realm-object-store/blob/b597945d068856a7b7a5bb8e5d68d6403ab87961/tests/sync/sync_manager.cpp#L49)

**Comment by simonask** [comment]
I can reproduce a segfault through the JS binding when running many unit tests that start and stop many sessions.

The crash only happens when the stop policy in `js_sync.hpp` is `SyncSessionStopPolicy::AfterChangesUploaded`. If I change it to `SyncSessionStopPolicy::Immediately`, everything goes well (but of course terminates sessions immediately without waiting for pending changes to be uploaded).

It seems that `SyncManager::reset_for_testing()` must be extended to wait for all threads that are currently blocking on `wait_for_upload_complete_or_client_stopped()` to return. This way may have to happen in `SyncClient::~SyncClient()` between calling `sync::Client::stop()` and deleting the `sync::Client` object.

**Comment by bdash** [comment]
One thing that stands out is the [sync transaction callback that `SyncSession` registers](https://github.com/realm/realm-object-store/blob/28ac73d8881189ac0b6782a6a36f4893f326397f/src/sync/sync_session.cpp#L374-L380) doesn't respect the warning found in the documentation for `sync::Session::set_sync_transact_callback`:

> CAUTION: The specified callback function may be called before the call
> to bind() returns, and it may be called (or continue to execute) after
> the session object is destroyed. The application must pass a handler
> that can be safely called, and can safely continue to execute from the
> point in time where bind() starts executing, and up until the point in
> time where the last invocation of `clint.run()` returns. Here, `client`
> refers to the associated Client object.

The body of this callback is a frequent crash site when reproducing the crash per @simonask's instructions, with it being called after the `SyncSession` has been deallocated.

**Comment by nhachicha** [comment]
AFAICT the current implementation of [SyncManager::reset_for_testing()](https://github.com/realm/realm-object-store/blob/master/src/sync/sync_manager.cpp#L141) only clears the Map holding the users... Is it possible to delete the _metadata_ Realm created to store the users as well? 

I started the migration of the SyncUser for Java using the OS Users & this is blocking my tests

**Comment by bdash** [comment]
Yes, that's what this issue tracks.

**Comment by austinzheng** [comment]
Does this still need to be done? @alazier

**Comment by alazier** [comment]
dont think so?

**Comment by nhachicha** [comment]
@austinzheng we still need this feature (deleting the metadata table) in Java (for unit test the [SecureUserStore](https://github.com/realm/realm-android-user-store))
