### ISSUE TITLE
Move keychain_helper to Cocoa bindings

### ISSUE THREAD

**Issue by stel** [realm/realm-object-store#216]
Is there a reason to keep keychain helper methods for storing the encryption key in ObjectStore rather than move it into cocoa bindings? It's used only when loading `SyncMetadata` (https://github.com/realm/realm-object-store/blob/master/src/sync/impl/sync_metadata.cpp#L73) and can be specified from bindings via `SyncManager->configure_file_system(...)`.

/cc @austinzheng, @bdash, @jpsim

**Comment by austinzheng** [comment]
The idea is that it can be used for any binding that runs on an Apple platform (e.g. React Native), not just ObjC/Swift.

**Comment by stel** [comment]
Ah yes, makes sense. Thanks!
