### ISSUE TITLE
Linux needs a event loop implementation to support sync tests

### ISSUE THREAD

**Issue by bdash** [realm/realm-object-store#229]
Currently Linux uses the default event loop implementation for which every operation is simply a no-op.  Some sync tests currently fail on Linux due to them relying on having a working event loop. It'd be useful to be able to run these tests on CI as it's currently much easier to do on Linux than Android.

The easiest path may be to default to the libuv event loop implementation used by Node when on Linux. I'm not sure if there's any downsides to doing that.

**Comment by tgoyne** [comment]
An eventloop that implements just enough to support running the tests would probably only be about 20 lines of code, but even so I'm not sure it's worth bothering rather than just making a real one a hard dependency, especially since there's non-test functionality that requires one anyway.
