### ISSUE TITLE
logout() needs a way to observe or be notified when logout has completed

### ISSUE THREAD

**Issue by dhmspector** [realm/realm-object-store#231]
As of version 2.0.4 calling logout no longer results in an immediate logout of the user object, (calling ```currentUser().logOut()``` doesn't result in ```currentUser == nil)``` and there isn't a  is there a notification available for when the logout process has completed. 

Previously, in v2.0.2 calling logout on currentUser was immediate… now currentUser is still a live object for a while.  Since it's still alive, one cannot reliably check SyncUser.currentUser() to see if you have a stored credential to see if you should, for example, show  login/credentials form or if you’re really still logged in.

**Comment by alazier** [comment]
Sounds like a bug. Logout should be immediate. We had a similar issue on the JS binding - problem was that we were including users which were flagged for removal when looking at the list of active users. Discounting these users fixes the issue

**Comment by jpsim** [comment]
@dhmspector or @austinzheng can one of you investigate and determine where this bug lives, either object store or cocoa?
