### ISSUE TITLE
Since logout now waits until pending sync ops are done - what happens if the device is offline?

### ISSUE THREAD

**Issue by dhmspector** [realm/realm-object-store#232]
Apropos of issue https://github.com/realm/realm-object-store/issues/231, another question comes up:  what happens if you call logOut() on a user object and the device is offline?   Since logout is not complete until any pending sync operations are completed,  is the app, for all intents and purposes, hung? (From a single test with my "TeamWork app" it looks like the answer is "yes.")

How should developers deal with this situation, since, as in the previously mentioned issue, the user object will still be live until the logout process is complete...? Any app that needs to present a login panel of some kind and checks for a stored credential to know what to do (show the panel or just proceed into the app) will not have a clear path on a correct course of action.

**Comment by astigsen** [comment]
We have talked about the need for a "soft" logout before. A soft logout would mean that it is entirely managed by the objectstore in the background. When the user logs out there may still be unsynced changes, so the background process could keep the user profile and realms around until it get confirmation that everything is synced and _then_ clean up (but this would not be available to you at the user level, they would have to log in again to access their Realms).

In this way it would not matter if you are on- or offline when logging out. But it does mean that Realms of users who have logged out can stay around for a potentially long time (if there is no connectivity), which in some cases can be a security risk. So this is why we also need to be able to do a "hard" logout, where you can be sure that everything gets removed.

**Comment by jpsim** [comment]
This is already handled by the "stop policy": https://github.com/realm/realm-object-store/blob/e27a506074846946bc9fbdf2b0e3530e57bed6e8/src/sync/sync_manager.hpp#L44-L48

```cpp
enum class SyncSessionStopPolicy {
    Immediately,                    // Immediately stop the session as soon as all Realms/Sessions go out of scope.
    LiveIndefinitely,               // Never stop the session.
    AfterChangesUploaded,           // Once all Realms/Sessions go out of scope, wait for uploads to complete and stop.
};
```

**Comment by austinzheng** [comment]
Right now, the stop policy only governs what happens when the Realm goes out of scope or is explicitly closed (on bindings that support it). We have a couple of options:

* Stop policy also governs how the Realm behaves when the user logs out (maybe including `LiveIndefinitely`?)
* Stop policy governs how the Realm behaves by default when the user logs out, but can be overriden
* A completely separate stop policy setting determines what happens when the user logs out; that and the existing settings are orthogonal
* Something else?

**Comment by dhmspector** [comment]
this probably needs to be referenced in the API doc's section on logout behavior so dev's can make an informed choice on what happens - not mentioned anywhere that I recall seeing, so I didn't know (hence this issue  :)  )

**Comment by jpsim** [comment]
It's not actually user-configurable in any of the bindings at the moment.
