### ISSUE TITLE
Support opening synced read-only realms

### ISSUE THREAD

**Issue by alazier** [realm/realm-object-store#234]
I'm trying to open the admin realm read-only for use in the global notifier, as client side changes to this realm have caused continues issues. When making this change I am getting this error:
`Cannot create asynchronous query for read-only Realms`

Not sure what we would need to do to fix this and other issues to open the admin realm as read-only but we should definitely be preventing changes from coming in from clients. If the server were capable of preventing incoming changesets then this would be another way to avoid these issues.

@tgoyne @mrackwitz @bigfish24 @kristiandupont

**Comment by jpsim** [comment]
The current meaning of "read-only" assumes that a Realm is on read-only media. Async queries rely on handover, which requires writing to a lock file: realm/realm-core#1317.

It might be beneficial to decouple the concepts of "read-only" as "not writable by this client" from "not in a writable location", especially with the new concept of access control where a user may not have write permission to the Realm, even though they have write permission to the local file.

**Comment by jpsim** [comment]
Fixed in cocoa: realm/realm-cocoa#4910
