### ISSUE TITLE
config.schema is incorrect after sync

### ISSUE THREAD

**Issue by alazier** [realm/realm-object-store#236]
This is causing issues on the global notifier when opening using a dynamic schema. This might also cause issues in other cases where the schema is not updated after synced schema changes come in.

**Comment by bdash** [comment]
I think the intent is for `Realm::schema()` to return the current schema, including any changes that were made by other clients in additive schema mode, while the configuration's schema remains unchanged.

@tgoyne, can you confirm this?

**Comment by tgoyne** [comment]
"causes issues" is insufficient information to say anything about what should be done to solve the problem.

**Comment by alazier** [comment]
Its not clear this is actually causing problems. The problem we have is that when a partial schema is first loaded/initialized on a client, the server throws an exception when the attempting to load the full schema. @mrackwitz and @radu-tutueanu can provide more information.

**Comment by radu-tutueanu** [comment]
I think this is an issue that you are referring to: https://github.com/realm/realm-sync-services/issues/529
In this case, only the client is affected(the globalListener inside the realm-object-server)
When the crash occurs, it means that for some reason it is using the partial schema, although the local __admin.realm file already exists from previous runs with the complete schema.
After the crash happens, the sync protocol can no longer handle incoming changesets.

**Comment by tgoyne** [comment]
The change in https://github.com/realm/realm-js-private/pull/227 looks correct to me. Even with the additive schema mode a schema version must always be set.
