### ISSUE TITLE
Prevent two different processes from opening the same sync'ed realm

### ISSUE THREAD

**Issue by kristiandupont** [realm/realm-object-store#237]
Right now there is nothing preventing it but it will cause undefined behavior..

**Comment by jpsim** [comment]
It's essentially impossible for this to happen on iOS/tvOS/watchOS due to Realm managing where the synced Realm is stored on the file system, but this could feasibly happen on macOS. I don't know about Android.

**Comment by bdash** [comment]
It looks like realm/realm-core#2313 is laying the groundwork for this.

**Comment by kspangsege** [comment]
Thanks for spotting the connection @bdash :-)

**Comment by bdash** [comment]
realm/realm-core#2313 was in the realm-core v2.2.0 release, which should eliminate any potential for undefined behavior.
