### ISSUE TITLE
Metadata persistence should allow `User` lookup by server

### ISSUE THREAD

**Issue by austinzheng** [realm/realm-object-store#245]
Right now `User`s are stored with the primary key being the user identity. This should change so that multiple users with the same ID but different servers can be stored. A particular user should be uniqued based on both its identity _and_ its server, if the server is defined. @astigsen

**Comment by joshuapinter** [comment]
Yes please. I started with just an IP address to the server and I switched to a domain name, now it won't let me log in with the same user credentials. I guess I'll switch back for now.

**Comment by Montrazul** [comment]
Same here. We added an SSL certificate for a domain and we switched from ip to domain with https and realms protocols. Now we cant login: 

`terminating with uncaught exception of type std::invalid_argument: Cannot retrieve an existing user specifying a different auth server.`

**Comment by kunalchaudhary23** [comment]
Any updates on this issue? We're having the same problem after adding HTTPS support.

**Comment by austinzheng** [comment]
Thanks for commenting. We understand that this is important for our customers and are (internally) exploring ways to improve this feature. I'll post in this thread once we have anything to show you all.

**Comment by austinzheng** [comment]
Duplicate of #397.

**Comment by joshuapinter** [comment]
If I'm not mistaken, @austinzheng, this looks to be fixed now, correct? We're able to switch our servers to use https or a domain name without issue?

Thanks!

**Comment by bdash** [comment]
Yes, this was fixed at the object store level in #497. The fix was released in the Cocoa SDK in [v2.9.0](https://github.com/realm/realm-cocoa/releases/tag/v2.9.0). I think it's also been released in several other SDKs by now, but I don't know in which versions off the top of my head.

**Comment by austinzheng** [comment]
As @bdash said, you'll be able to create different users with different URLs but the same identity without problem. This covers cases including (but not limited to) http vs https, different ports, and IP versus hostname.

Note that we don't do anything special to distinguish URLs (e.g. a user created using https://realm.example.org is considered a different user than one created using http://realm.example.org). This won't cause your app to malfunction in any way even if you use both users simultaneously, but you shouldn't (e.g.) expect them to share the same local Realm file or automatically log the other out when one is logged out.

Hope that helps, and as always thanks for using Realm!

**Comment by joshuapinter** [comment]
@austinzheng Thanks for the explanation! Any idea what would happen if we switch from an IP address to a domain address? Would Realm consider that a different user?

**Comment by austinzheng** [comment]
The Realm Object Server (which is what matters for the purposes of your question) would consider them the same user, as you'd probably expect.

The client device wouldn't know about the IP to domain address switch, so you'd have to create/log in the user using the new URL, and if you opened a Realm using the domain address user it would download a new copy.

We are considering APIs to make this process less awkward (for example, APIs to indicate to the sync subsystem that a user at URL x has moved to URL y), and welcome any feedback!

**Comment by joshuapinter** [comment]
@austinzheng Right, that makes sense. So maybe after that change they need to do a full refresh from the Realm Object Server but that's a minor inconvenience (in my case at least).

Sounds great, guys. Can't wait to try it out. Thanks! 👍
