### ISSUE TITLE
Improve URL handling

### ISSUE THREAD

**Issue by austinzheng** [realm/realm-object-store#246]
URL handling should be improved:

* Better URL handling than just looking at raw strings; for example `http://127.0.0.1` and `127.0.0.1` shouldn't be considered different for the purposes of specifying an auth server URL
* Better handling of protocols. Right now if you use the wrong protocol to create a `SyncUser` you get a cryptic error message. @astigsen

**Comment by alazier** [comment]
We may need to address the 2nd bullet separately on each platform as that is where the network calls are made and from where the error originates (at least on js).
