### ISSUE TITLE
Unable to set the path for the sync_metadata realm

### ISSUE THREAD

**Issue by radu-tutueanu** [realm/realm-object-store#263]
We should be able to specify where the sync_metadata realm is created.

We have and issue in the ROS that requires us to change the current working directory when the ROS is started as a service so that it would have write access to the working directory.

@bdash @mrackwitz

**Comment by alazier** [comment]
This is an object store issue @austinzheng

**Comment by alazier** [comment]
I guess we could support this in the JS binding though - we could add a static property
`Realm.Sync.objectServerDirectory` which would set the root dir used for the object server including the metadata dir. You would only be able to set this before making any other Realm api calls or things would get pretty messy.

**Comment by austinzheng** [comment]
The metadata Realm (and all helper directories) are created within whatever folder you specify when you call `SyncManager::configure_file_system()`. Do you want more fine-grained control?

**Comment by alazier** [comment]
Right now we don't expose that through the JS binding - `Realm.Sync.objectServerDirectory` would simply make that call. Right now that can only be called once though before any other methods are called. We could instead have a method `Realm.Sync.init(options)` which would allow you to pass a custom path - this would get called automatically with the default options when needed if not called explicitly to match the current behavior.

**Comment by austinzheng** [comment]
That seems like a decent solution to me, but I'm not well-versed in JS conventions. Is there an alternative that you'd prefer instead? I'm happy to build something out, I just need to understand the context.

**Comment by alazier** [comment]
If we don't need to be able to change the path after startup, and we are ok having the metadata path fixed relative to the root ros path which is configurable then the current os apis are probably sufficient to support this in JS. If we need anything beyond this we will probably need to add stuff to os.

**Comment by radu-tutueanu** [comment]
Thanks, @alazier and @austinzheng . Setting the path at startup is good enough. I'll move the issue to realm-js.

**Comment by bdash** [comment]
@radu-tutueanu, does that mean there's nothing to do here?

**Comment by radu-tutueanu** [comment]
That is right. https://github.com/realm/realm-js/issues/720
