### ISSUE TITLE
Custom binding data in Sync classes

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-object-store#264]
Given that the ObjectStore manages the lifecycle of various Sync classes (Especially `SyncSession` and `SyncUser`), Java and .NET have problems hooking into those classes if they wish to communicate something back to the binding.

Java has a specific use case regarding the error handler. 

1) Opening a `SharedRealm` requires the `SyncConfig`, which in turn requires an error handler needed by the `SyncSession`. However, we have no reference to the Java Session object when the error handler is created, which prevents us from setting up the error handler correctly as it has no way of setting up the communication between the C++ `SyncSession` and the Java `SyncSession` (which doesn't exist yet).

2) I believe @fealebenpae have similar problems also for `SyncUser`. He can expand on the details if needed.

**Solution**
Have a field or map of generic fields that can be filled with anything. Not entirely sure what the best approach is. In our case we need to save a reference to a `jobject` that represent the Java Session, but I'm not entirely sure how to generalize this.

**Comment by bdash** [comment]
I'd appreciate if you could go into more detail as to what is needed and why. It's not immediately obvious to me what constraints Java and .NET have that make the current approach problematic, or what purpose the extra fields you mention would serve.

**Comment by cmelchior** [comment]
```
        m_java_session_ref = env->NewGlobalRef(java_session_obj);
        jobject global_obj_ref_tmp(m_java_session_ref);

        auto error_handler = [&, global_obj_ref_tmp](int error_code, std::string message, realm::SyncSessionError) {
            JNIEnv *local_env;
            g_vm->AttachCurrentThread(&local_env, nullptr);
            jclass java_session_class = local_env->GetObjectClass(global_obj_ref_tmp);
            jmethodID notify_error_handler = local_env->GetMethodID(java_session_class,
                                                                    "notifySessionError", "(ILjava/lang/String;)V");
            local_env->CallVoidMethod(global_obj_ref_tmp,
                                      notify_error_handler, error_code, env->NewStringUTF(message.c_str()));
        };
```

This is the current code for the error handler where the Java binding control the session itself. `g_vm` is a global variable, but `java_session_obj` needs to be available for this to work.

However after giving it some thought, I think it might be possible to work around this is Java by creating the Java `SyncSession` object before opening the Realm.

**Comment by fealebenpae** [comment]
In .NET we need to store extra state in the `Session` object such as event handlers and that's why we cannot always create a thin managed wrapper around `SyncSession` like we do for `SyncUser` for example.

I've already worked around this in .NET by having a global dictionary that maps between the `SyncSession` object and the .NET `Session` object, but I was rather hoping to be able to avoid the locking that approach entails.

**Comment by bdash** [comment]
@cmelchior, is the workaround used by .NET applicable to Java?

**Comment by cmelchior** [comment]
I found another way, but creating the Session object in Java before the `SharedRealm`, so this is no longer needed I think. I'm running into other problems though.

**Comment by bdash** [comment]
Ok. There still seems like some value in providing something like this, but since it's not blocking anything let's not prioritize it right now.
