### ISSUE TITLE
Require migration function if any schema changes could produce duplicate PKs

### ISSUE THREAD

**Issue by stel** [realm/realm-object-store#271]
When performing migration for primary key property from optional to required and not providing a migration function the uniqueness of primary keys is lost and no error is provided. Migration function should be required in this case and should handle the primary key migration by itself.

Related to https://github.com/realm/realm-object-store/pull/250 and https://github.com/realm/realm-object-store/pull/252, https://github.com/realm/realm-cocoa/issues/4370

**Comment by bmunkholm** [comment]
Outdated.
