### ISSUE TITLE
Sync sessions with "wait for upload" policy never die if they cannot connect to the server

### ISSUE THREAD

**Issue by bdash** [realm/realm-object-store#292]
In realm/realm-js-private#235 it was observed that if a sync session is created with `SyncSessionStopPolicy::AfterChangesUploaded` and it is unable to connect to the server, the session will linger in the dying state indefinitely. The object store should ensure that such sessions die in a timely manner.

**Comment by austinzheng** [comment]
How can we tell if such a session is unable to connect to the server? Is there an error message that `sync` reports via the error callback? @kspangsege

**Comment by kspangsege** [comment]
@austinzheng Is this still an issue?

Anyway, I am not entirely sure what you are asking about. One thing that can happen, is that the client tries to contact the server, but nothing happens for a long time (neither success nor failure). If this is the case that you are referring to, then I believe it will be fixed by https://github.com/realm/realm-sync/issues/1172.

**Comment by morten-krogh** [comment]
Alternatively, wait_for_upload_complete and siblings should have a timeout argument.

**Comment by kspangsege** [comment]
> Alternatively, wait_for_upload_complete and siblings should have a timeout argument.

Do you think that would be a superior solution? I don't see it.

**Comment by morten-krogh** [comment]
Superior to what? Heaertbeats. It is two different things. Upload could take forever for other reasons. 

I can see that you want to say "lets us wait for upload/download completion, but if it takes more than 10 seconds, drop the wait". Almost any wait in real life would work like that.

The the app can choose another code path and UI message to the user.

Of course, a timeout argument in the wait_for_* is not the only way of achieving that.
The app can have its own timeout and cancel the wait or let it continue forever and disable the
callback.

**Comment by bdash** [comment]
To restate the problem we're trying to address here:

`SyncSession` has the concept of a dying state that it enters when the binding has dropped all references to a given session. Once in this state the session waits for any pending changes to upload before unregistering itself and being destroyed. What is happening in this particular test is that since the connection is never established, the upload never signals completion, and so the `SyncSession` remains in this dying state indefinitely. At the object store level, a `SyncSession` instance is waiting on `realm::sync::Session::async_wait_for_upload_completion` to call the callback it was passed.

At the realm-sync level, the reason the callback is never called is that the `Session` is still attempting to perform the upload, but the attempts to connect to the server are failing. @kspangsege notes in https://github.com/realm/realm-js-private/issues/235#issuecomment-266166889 that each failed connection attempt is reported to the error handler.

**Comment by kspangsege** [comment]
Thanks @bdash . I can now answer @austinzheng 's question:

> How can we tell if such a session is unable to connect to the server? Is there an error message that sync reports via the error callback? @kspangsege

Yes, every connection failure (during or after establishment) will be reported via the error handler. This should give you the necessary opportunity to terminate the "dying" phase of the `SyncSession`.

This assumes that https://github.com/realm/realm-sync/pull/1015 is available in the version you use.

**Comment by austinzheng** [comment]
Yeah, I think that should be sufficient. Do you know which specific error or range is reported? `disabled_session`, maybe? None of them stand out.

**Comment by morten-krogh** [comment]
Yes, my comment was off topic. Sorry.

**Comment by kspangsege** [comment]
> Do you know which specific error or range is reported? `disabled_session`, maybe? None of them stand out.

I believe it could be almost anything depending on when and how the error occurs. It need not be one of the protocol level errors (https://github.com/realm/realm-sync/blob/master/doc/protocol_16.md#error-codes). It could well be a system-level error such as `ENETDOWN`, `ENETUNREACH`, `ENETRESET`, `ECONNABORTED`, or `ECONNRESET`. Also see https://github.com/realm/realm-sync/blob/8cd7e2ca375d8321f16daf70e0bbd87406058318/src/realm/sync/client.hpp#L310.

If you are in the dying phase, can't you simply take any error to mean "end of dying phase"?

**Comment by austinzheng** [comment]
Sure, I think that makes sense. I can still ignore the not-actually-errors, like `connection_closed`, right?

**Comment by kspangsege** [comment]
Also, in some cases, there will not be an error report for a long time, even though the establishment  of the connection is ultimately doomed. I expect this problem to be solved by  https://github.com/realm/realm-sync/issues/1172.

**Comment by kspangsege** [comment]
> I can still ignore the not-actually-errors, like `connection_closed`, right?

Maybe.

I'm not sure exactly what you are waiting for in the dying phase, but I think there are generally two approaches that make sense:

 - Terminate "dying" phase on report of any error. This ensures reliable termination.
 - Only terminate "dying" phase on report of a fatal error (as specified by the `fatal` argument to the error handler). This will sometimes extend the lifetime of the "dying" phase, but potentially at the expense of a risk of hanging indefinitely.

**Comment by austinzheng** [comment]
I agree. The caveat with #1 is that there exists the possibility of preventable data loss that doesn't with #2 (since, right now, Realms for users that are logged out are deleted upon next app launch). I think the rare chance of hanging indefinitely is preferable to accidentally losing a logged-out user's data. Perhaps in the future we can implement a more thorough system that provides the option of background-syncing a "dying" Realm across multiple app launches and only then destroying it.
