### ISSUE TITLE
Locking scheme in SyncManager

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-object-store#293]
Right now all methods in the SyncManager follow this pattern:

```
void SyncManager::method()
{
    std::lock_guard<std::mutex> lock(m_mutex);
    // logic
}
```

I assume this is to make it threadsafe. If there are other reasons I am not aware of them.

This pattern is problematic if we want to expose callbacks for various events, like state changes, and these events call back into the OS (which will deadlock). 

Example 1: Java wants to allow the Java binding to control the session lifecycle. So we added a callback for when the session was created and destroyed so we could react to it from Java. In our case we wanted to control if the session should be revived automatically when created and we needed the destroy method for cleanup.

Example 2: Java wants to log session `PublicState` changes for debugging purpose. Exposing a callback is possible and pure logging doesn't result in deadlock, but it opens up the chance, which is  a problem https://github.com/realm/realm-object-store/pull/282#issuecomment-266152044. 

I would suggest that we switch to a reentrant lock which would allow reentry from the same thread.

1) The argument has been given that allowing reentrant locks from the same thread could result in deadlocks from lock inversion, but given that lock inversion can only happen if we expose other locks from the SyncManager, that doesn't seem to be a problem right now?

2) There is also performance concerns. I don't know how big the difference is in performance, but given that none of the SyncManager methods are supposed to be used in hot paths, I don't think this is an issue? 

Given that the current locking scheme causes real problems now vs. hypothetical problems from switching to reentrant locks, I would suggest switching to reentrant locks. Reentrant locks would also fit the `synchronized` keyword in Java better which is commonly used for controlling concurrent access to a class like SyncManager.

Thoughts @bdash @tgoyne @austinzheng ?

**Comment by tgoyne** [comment]
> The argument has been given that allowing reentrant locks from the same thread could result in deadlocks from lock inversion, but given that lock inversion can only happen if we expose other locks from the SyncManager, that doesn't seem to be a problem right now?

No, it does not require that. On thread A, java code acquires a lock, then calls something on SyncManager, while on thread B SyncManager invokes a callback which attempts to acquire the lock thread A is holding. Even if both of the locks involves are reentrant this is a deadlock.

Reentrant locks "fix" the most trivial situations but do not free you from having carefully keep track of which locks are held at any given point, which is fundamentally impossible when the relevant locks aren't even all in the same project.

**Comment by cmelchior** [comment]
Good point, I did not consider that use case. But as far as I know, the SyncManager does not contain any threading by itself? The Client/SyncSession will most likely run on another thread, but all the events I have described are controlled by the SyncManager, so they will not happen on another thread.

**Comment by fealebenpae** [comment]
We've seen numerous crashes related to `std::mutex` errors when running Node.js tests until we narrowed down the incantation needed to correctly reset the SyncManager state for tests. I'm worried this will regress at some point in the future.

**Comment by bdash** [comment]
The crashes when resetting between tests were a bug that has been fixed. They weren't related to locking in any way, the mutex just happened to be the first thing that was touched on a deallocated object.

**Comment by bdash** [comment]
I don't think this is something we intend to revisit at this point as the current design does not appear to be causing problems, and there's not an obviously superior alternative design.
