### ISSUE TITLE
Cannot retrieve an existing user specifying a different auth server

### ISSUE THREAD

**Issue by stel** [realm/realm-object-store#296]
`SyncManager` throws an uncaught exception (https://github.com/realm/realm-browser-osx-private/issues/147) when logging in the user with the same credentials but with a different server URL (when the same instance of the server is launched on another hostname).

**Comment by austinzheng** [comment]
c.f. https://github.com/realm/realm-object-store/issues/245

**Comment by ajonno** [comment]
any eta on a fix ? we're assessing Realm Object Server at moment...

**Comment by austinzheng** [comment]
We intend to fix this as soon as we can, but can't provide any concrete dates at this point.

**Comment by Redth** [comment]
+1 here... this just bit me :(

**Comment by dannygrob** [comment]
+1 here, want to change port numbers, but crashes old clients

**Comment by stel** [comment]
@austinzheng, @bdash is there anything we can do to get some progress on this? According to crash reports we're getting for Browser, more and more users are getting affected by this issue when switching to SSL.

**Comment by austinzheng** [comment]
I can start working on this for 3.0, since everything else on my to-do list is in decent shape right now.
