### ISSUE TITLE
Support "read" permission only with synced Realm

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-object-store#312]
With sync, we can get a different combination of read, write, and manage permissions for another user's Realm.

Right now, we get an error if we try to open a realm with just read permissions (the session throws permission denied exception). I haven't investigated what happens when we try to open a write-only realm, but I guess it's not supported either.

I assume that, in order to exercise the `manage` permission, we'll just have to open the other user's management realm, which I guess should be done by the binding.

**Comment by astigsen** [comment]
> Right now, we get an error if we try to open a realm with just read permissions

This sounds like a bug. You should obviously be able to open it if you have permissions to read it. It should only fail if you try to write to it.

**Comment by nirinchev** [comment]
It could be classified as a bug that stems from lack of support for that case. Right now, OS is not aware of the fact that synced realms may be read only, so it doesn't take any steps to prevent writes - @jpsim  explained that creating the schema will trigger a write, which in turn invalidates the session. Here's a transcript from the discussion on Slack ([internal link](https://realmio.slack.com/archives/sync-bindings/p1483455473000049)).

**Comment by mrackwitz** [comment]
As we differentiate in the product repo between the different permissions and the discussion here so far has been about support for read-only Realms, which also seems to be easier to achieve, I've changed this issue to track only what would be required by https://github.com/realm/product/issues/195.
