### ISSUE TITLE
could not create WeakRealmNotifier ALooper message pipe: Too many open files

### ISSUE THREAD

**Issue by Miger88** [realm/realm-object-store#319]
hello,
I try to evaluate different databases inside one android app- Therefore I created different scenarios. The scenarios are different in the size and count of objects I will store.

All calls to the realm database came from a class I called "RealmDataManager". Inside this I implement differend methods which I need for my evaluation.

I use a IntentService which gets started from my Mainactivity. Inside my IntentService I defined the different scenarios and what to do for each. 

At the Moment I have one problem. After my 4th Szenario (from 90 szenario's) I got the  following Output in Logcat,

> 01-06 13:51:54.957 14995-15287/de.gerding.dbcompare E/REALM: could not create WeakRealmNotifier ALooper message pipe: Too many open files
01-06 13:51:54.959 14995-15287/de.gerding.dbcompare E/REALM: could not create WeakRealmNotifier ALooper message pipe: Too many open files
01-06 13:51:54.963 14995-15012/de.gerding.dbcompare E/Parcel: dup() failed in Parcel::read, i is 0, fds[i] is -1, fd_count is 1, error: Too many open files
01-06 13:51:54.966 14995-15287/de.gerding.dbcompare E/REALM: could not create WeakRealmNotifier ALooper message pipe: Too many open files
01-06 13:51:54.967 14995-15287/de.gerding.dbcompare E/REALM: could not create WeakRealmNotifier ALooper message pipe: Too many open files
01-06 13:51:54.972 14995-15287/de.gerding.dbcompare E/REALM: could not create WeakRealmNotifier ALooper message pipe: Too many open files
01-06 13:51:54.974 14995-15287/de.gerding.dbcompare E/REALM: could not create WeakRealmNotifier ALooper message pipe: Too many open files
01-06 13:51:54.980 14995-15012/de.gerding.dbcompare E/Parcel: dup() failed in Parcel::read, i is 0, fds[i] is -1, fd_count is 1, error: Too many open files
01-06 13:51:54.982 14995-15012/de.gerding.dbcompare E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -22
01-06 13:51:54.982 14995-15012/de.gerding.dbcompare I/Adreno: QueueBuffer: queueBuffer failed
01-06 13:51:54.982 14995-15012/de.gerding.dbcompare W/OpenGLRenderer: swapBuffers encountered EGL_BAD_SURFACE on 0x7f82d04940, halting rendering...
01-06 13:51:54.984 14995-15287/de.gerding.dbcompare E/REALM: could not create WeakRealmNotifier ALooper message pipe: Too many open files
01-06 13:51:54.985 14995-15287/de.gerding.dbcompare E/REALM: could not create WeakRealmNotifier ALooper message pipe: Too many open files
01-06 13:51:55.014 14995-15287/de.gerding.dbcompare E/REALM: could not create WeakRealmNotifier ALooper message pipe: Too many open files
01-06 13:51:55.016 14995-15287/de.gerding.dbcompare E/REALM: could not create WeakRealmNotifier ALooper message pipe: Too many open files

...

Can you help me to figure out what I should change to solve this?

It's not a big problem, it looks like it works although this logcat output gets spammed. But I am not sure if it works for a long time. In my mainactivity I show an ProgressDialog when I start my "MessService", and this ProgressDialog in style circle doesn't move anymore when I got the logcat spam. 

I will attach you some of my classes.
RealmDataManager - where all calls to the database are implemented.

MessService - where all scenarios are defined and you can see how I use the RealmDataManager
I take some comments inside my MessService so that not alle scenarios are used at the moment because some scenarios needs long time and this is not fine for debugging.

RealmCANDaten - one of my two objecttypes stored in the database

RealmFahrt - the other objecttype stored in the database

If you need more information for reproducing please let me know that. I hope we can fix this issue together.

[Logcat.txt](https://github.com/realm/realm-object-store/files/689986/Logcat.txt)
[MessService.txt](https://github.com/realm/realm-object-store/files/689988/MessService.txt)
[RealmCANDaten.txt](https://github.com/realm/realm-object-store/files/689989/RealmCANDaten.txt)
[RealmDataManager.txt](https://github.com/realm/realm-object-store/files/689990/RealmDataManager.txt)
[RealmFahrt.txt](https://github.com/realm/realm-object-store/files/689987/RealmFahrt.txt)

**Comment by kneth** [comment]
@Miger88 I believe that https://github.com/realm/realm-java is better place to ask (object store is primarily an aux. library) so I have created https://github.com/realm/realm-java/issues/4002
