### ISSUE TITLE
Fix Android sync builds

### ISSUE THREAD

**Issue by emanuelez** [realm/realm-object-store#327]
If one tries to run:

```
workflow/build.sh android sync
```

then CMake will fail for not being able to find Git.
This happens because the [Android toolchain](https://github.com/realm/realm-object-store/blob/master/CMake/android.toolchain.cmake#L1536) file sets `CMAKE_FIND_ROOT_PATH_MODE_PROGRAM ` to `ONLY`, which forces CMake to [look for git](https://github.com/Kitware/CMake/blob/64130a7e793483e24c1d68bdd234f81d5edb2d51/Modules/ExternalProject.cmake#L1755) in the NDK.

One possible solution could be to use URLs for the source tarballs in the Github releases.
Modifying the toolchain might work as well, but setting `CMAKE_FIND_ROOT_PATH_MODE_PROGRAM` to `BOTH` might cause some unexpected issues.

**Comment by bdash** [comment]
For now I think we can say that Android sync builds must use existing local source trees for core and sync, rather than relying on our attempts to automatically check out given versions. This'd require adding some logic to the Jenkinsfile to check out the appropriate versions of core and sync.

**Comment by kneth** [comment]
Currently it is not possible to build the sync test for Android. The YAML library doesn't exists in Android NDK so we will have to build it too.
