### ISSUE TITLE
Add tests for object accessors

### ISSUE THREAD

**Issue by fealebenpae** [realm/realm-object-store#342]
The template-based APIs of `realm::Object` are not exercised in CI - `create`, `get_property_value`, `set_property_value`, and `get_for_primary_key`.

**Comment by austinzheng** [comment]
This is a requirement for writing tests for #375, so I'll spend some time looking into it.

**Comment by austinzheng** [comment]
#394 addresses this at least partially.

**Comment by bdash** [comment]
#443 fleshed this out further.
