### ISSUE TITLE
Moves and Deletions of Objects in a List fire multiple notifications

### ISSUE THREAD

**Issue by ianpward** [realm/realm-object-store#373]
why when I delete just 1 item (index 4), there are actually 2 deletions, and 1 insertion: changes:  { deletions: [ 3, 4 ], insertions: [ 3 ], modifications: [] }
To limit the amount of API calls, I'd like to only make 1 DELETE call to my api.

@bdash @bigfish24 @tgoyne

**Comment by SogoGolf** [comment]
any eta on this being fixed ?

**Comment by nirinchev** [comment]
Duplicate of #391
