### ISSUE TITLE
SSL Support For Realm Object Server?

### ISSUE THREAD

**Issue by joshuapinter** [realm/realm-object-store#374]
Not sure if this is just a documentation issue, but I think it would be useful to have SSL support for the Realm Object Server as part of the default Getting Started path. I can't imagine anyone not wanting to use a secure connection when transmitting user data.

I'm a devops guys so getting port 9080 working with SSL is unknown territory. Any tips on this front would be useful. 

Thanks.

**Comment by bdash** [comment]
This repository is related to an internal component of Realm. If you need assistance with the Realm Mobile Platform, please [file an issue in the realm-mobile-platform repository](https://github.com/realm/realm-mobile-platform/issues/new).
