### ISSUE TITLE
sync::Session error_handler block not triggered, causing infinite 203 error

### ISSUE THREAD

**Issue by nhachicha** [realm/realm-object-store#379]
scenario:

- `SyncManager::shared().get_session` creates an ObjectStore wrapper around the `sync::Session`, let's say `std::shared_ptr<SyncSession> os_session; // (state WaitingForAccessToken)` 

- The `os_session`  is revived which cause `create_sync_session` to be called, this will create an error_handling [block](https://github.com/realm/realm-object-store/blob/1e20ebfa017a0bc03ad76e3b4e0aca44110d7c55/src/sync/sync_session.cpp#L515)

- The error handler lambda uses a `weak_ptr` obtained from the Shared Pointer `os_session`. 💣

- ObjectStore trigger the binding callback to get an `access_token`

- The binding close the SharedRealm, that releases the `RealmCoordinator`, this will call `dropped_last_reference_to_session` on `os_session` since the reference count drops to 0.

- The `dropped_last_reference_to_session` _deleter_ will store `os_session` as a `unique_ptr` in the `m_inactive_sessions` (now we have an inactive session in `WaitingForAccessToken`)
 
- Now we open a new Realm i.e `RealmCoordinator` this will call `get_session`, since we have an inactive session already, the method will create a new `shared_ptr` around the previous `os_session` [pointer](https://github.com/realm/realm-object-store/blob/1e20ebfa017a0bc03ad76e3b4e0aca44110d7c55/src/sync/sync_manager.cpp#L423) 💣
  
- Binding return with a valid `access_token`, we call `refresh_access_token` now we have an `Active` session

- Now we wait until the token expires (we don't actively refresh the token, for the sake of this use case).

- Now we try to upload a new commit using the active session. 

- Server will respond with `202` 

- The `sync::Session` error handler will trigger the defined `error_handler` [callback](https://github.com/realm/realm-object-store/blob/1e20ebfa017a0bc03ad76e3b4e0aca44110d7c55/src/sync/sync_session.cpp#L328)  however this callback will return because `weak_ptr` doesn't hold a valid reference anymore, because the first `shared_ptr` was destroyed, and we created a new one.

This will cause the `sync:Session` to never ask the binding to refresh the token, & it will keep trying to connect to the server with the old token, which will result on receiving `203` continuously

### option 1:

When `dropped_last_reference_to_session` is called instead of calling `close` 
call `close_if_connecting` if the state is `WaitingForAccessToken`.  `close_if_connecting` will unregister the session causing the SyncSession to be destroyed as long as the wrapped `sync:Session`. A future call to `get_session` will create a new session.

### option 2:

Inside the session error_handler, instead of checking if the weak_ptr is still holding a valid reference, use the `m_realm_path` to lookup if there's an existing session & use it to handle the error.

```
auto wrapped_handler = [this](std::error_code error_code, bool is_fatal, std::string message) {
        auto session = SyncManager::shared().get_existing_session(m_realm_path);
        if (session) {
            handle_error(SyncError{error_code, std::move(message), is_fatal});
        } else {
            return;
        }
```

this suppose a new method `get_existing_session` that will act similarly as `get_session` but unlike this one, doesn't take a `SyncConf` because we're only interested in returning an existing `Active` session or revive an `Inactive` one but doesn't create one. (btw, this method will also be helpful for the binding to lookup session by path).

*Note:* I implemented option 2 locally because I already add `get_existing_session` for other binding use case & it worked.

**Comment by austinzheng** [comment]
More generally, it looks like there's an issue with stale weak pointers if the session is moved into `dying` but then brought back to life.

**Comment by austinzheng** [comment]
I've begun putting together a potential fix based on option 2, but without the lock contention. I need to think about it some more.
