### ISSUE TITLE
Fine-grained Collection Notifications: Detect moves

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-object-store#391]
Right now moves are reported as delete/add pairs. Java UI controls like `RecyclerView` will animate moves differently than delete/add, so we should report them correctly as such.

If I recall correctly move detection is actually fairly expensive, so perhaps we need to be able to toggle this as well.

**Comment by tgoyne** [comment]
How high priority is this for Java? It's been stuck at "nice-to-have" for Cocoa.

**Comment by cmelchior** [comment]
Unknown at this point. I just created a java issue today to gauge interest. It is P2 for the time being.

**Comment by kneth** [comment]
I think we have the first request for it: https://github.com/realm/realm-android-adapters/issues/93

**Comment by stoneyMDB** [comment]
Moved to https://jira.mongodb.org/browse/RCORE-666
