### ISSUE TITLE
After Pod update getting this error "#include "binding_callback_thread_observer.hpp"" file not found

### ISSUE THREAD

**Issue by umarchohan** [realm/realm-object-store#409]
I have updated realm from 2.4.3 to 2.4.4 and getting this file error. Please fix this with me.

**Comment by jpsim** [comment]
Sometimes CocoaPods installation fails for a variety of reasons. Could you please try the following?

```
$ pod deintegrate
$ pod install --verbose
```

And share the full output of the following commands if you're still having trouble?

---

PS: this issue tracker is for the object store subsystem for Realm Cocoa. In the future, please file tickets here: https://github.com/realm/realm-cocoa/issues/new

**Comment by andy1247008998** [comment]
@umarchohan same problem here

Maybe we should stick to 2.4.3

**Comment by jpsim** [comment]
@andy1247008998 could you please follow the instructions from my previous comment?

**Comment by mayurdzk** [comment]
I'm facing the same issue. I tried deintegrating my pods and installing again. Didn't help.

There's another issue of the similar kind: 
'collection_notifications.hpp' file not found

**Comment by jpsim** [comment]
@mayurdzk please follow my instructions from my previous comment: https://github.com/realm/realm-object-store/issues/409#issuecomment-288140556.

@andy1247008998 @umarchohan I haven't heard back from you either after prompting to follow the two commands I posted: `pod deintegrate && pod install --verbose`.

**Comment by umarchohan** [comment]
@jpsim I have installed the older version.

**Comment by jpsim** [comment]
Will be closing this now. If anyone's still seeing installation problems with CocoaPods, [please open a new ticket on the realm-cocoa repo](https://github.com/realm/realm-cocoa/issues/new), posting the full output from the following commands:

```
pod cache clean Realm
pod cache clean RealmSwift
pod deintegrate || rm -rf Pods
pod install --verbose
rm -rf ~/Library/Developer/Xcode/DerivedData
```
