### ISSUE TITLE
Coordinator does not recognize a relative and an absolute path pointing to the same file

### ISSUE THREAD

**Issue by radu-tutueanu** [realm/realm-object-store#412]
The `RealmCoordinator::get_coordinator(StringData path)` function recognizes an absolute path and a relative path pointing to the same file as different paths, thus returns a different coordinator for each. This is a problem when using sync, as it would crash with a MultipleSyncAgents exceptions - you cannot bind the same file to the same url more than once.

It should recognize that the 2 paths point to the same file and return the same coordinator.

We hit this issue in the ROS: https://github.com/realm/realm-object-server/issues/999#issuecomment-288090478

```
libc++abi.dylib: terminating with uncaught exception of type realm::MultipleSyncAgents: Multiple sync agents attempted to join the same session
```

cc @bdash

**Comment by tgoyne** [comment]
We also don't attempt to handle unnormalized paths, symlinks, or any of the other numerous ways that you can get multiple paths which refer to a single file.
