### ISSUE TITLE
forCurrentlyOutstandingWork progress listeners report total work instead of changes only

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-object-store#427]
If I register a `forCurrentlyOutstandingWork` listener the output currently looks something like this:

1) Start with an empty database (uploaded = 0, uploadable = 0)
2) Write 80 bytes (0, 80)
3) Upload 80 bytes (80, 80)
4) Write 20 bytes (80, 100)
5) Register a `forCurrentlyOutstandingWork` Upload Listener.
6) This will now report (80, 100) immediately, which indicate it is 80% done already.

This doesn't seem consistent with the semantics the mode description. It would seem better to instead report (0, 20)

This seems trivially adjustable sine we just need to remember the initial values of  `uploadable/downloadable` value and subtract them from `downloaded/uploaded` values.

Thoughts @austinzheng ?

**Comment by austinzheng** [comment]
I'm okay with changing the semantics if it makes more sense and everyone agrees, but I think we should consider the solution described in https://github.com/realm/realm-sync/issues/1273 first.

**Comment by cmelchior** [comment]
Yes, this is a different problem than the one describe in 1273, but it is fine to wait fixing it until we have resolved #1273 since they might impact each other.

**Comment by bmunkholm** [comment]
Moved to https://github.com/realm/realm-core/issues/4611
