### ISSUE TITLE
Parsing transaction log with circular links is very slow when many objects exist

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-object-store#438]
from https://github.com/realm/realm-java/issues/4544 :

The schema looks like this:

```
      FILTER
           \
            \ *
             \/
             APP
             / /\
          * /   | 1
          \/    |
        FEED    |
       /\  \    | 
         \  \*  |
       1  \  \  |
           \ \/ |
            ITEM     
```

And modifying `filter.apps` then calling `commitTransaction()` freezes indefinitely.

Removing link `item.app` stops the crash. So I guess the problem is with the cycle from `FILTER -> APP -> FEED -> ITEM -> APP`, but Realm should be able to handle this, so it is a bug.

**Comment by beeender** [comment]
An Object Store test case shows the slowness of linking graph like this here https://gist.github.com/beeender/3759da9032ae9a199b3d6b9f2560d38e

It takes around 1 second on a desktop, but the original realm-java test project in https://github.com/realm/realm-java/issues/4544 takes around 1 minutes on the emulator.

This is abnormal, either my Object Store test case doesn't cover the case in the test project, or lots of IO involved in the testing running on the emulator.

Also, realm-java is calling `refresh()` after `commitTransaction()` to deliver changes right away for local commit, maybe that causing some locks switching?

When the problem happens on the emulator, the UI thread will be wait in `refresh()` and the `external_commit_helper` thread is taking all of the CPU.

BTW, it seems recent gradle add some new "clever" features to strip native symbols automatically, and that makes me very angry ...

**Comment by tgoyne** [comment]
Calling refresh immediately after committing causes that thread to block until notifications are ready, and the whole reason that isn't done automatically is that computing the changes may take a while.

**Comment by beeender** [comment]
Yes, the observation is links like that with that many of objects are slow ... but i don't have see any idea to optimize that a lot in this case -- basically the original test project needs to traverse all thousands of objects it created before.

But maybe, we should give user a flag `ignore_deep_link_changes` when adding the `Results` notifications block?
