### ISSUE TITLE
Offline Client Reset

### ISSUE THREAD

**Issue by simonask** [realm/realm-object-store#474]
Add support for resetting the Realm file when an `IncompatibleHistories` ("Incompatible histories. Nonupgradable history schema.") exception is thrown as a result of an non-migratable upgrade.

/cc @beeender @bdash

**Comment by beeender** [comment]
Will opening a non-sync Realm throw `IncompatibleHistories` exception? Or it is only for synced Realm?

**Comment by simonask** [comment]
Yes, unfortunately the same exception will be thrown, but with a different message. We can change it to be a separate exception type without much hassle, would that be an improvement?

**Comment by simonask** [comment]
You can also argue that there is very little the app can do with the `IncompatibleHistories` exception in the other case, so maybe a client reset is the correct course of action in all cases. It should probably configurable such that the opener of the Realm file decides what to do in this case.

**Comment by bdash** [comment]
@simonask, was your answer indicating that in general it's possible for `IncompatibleHistories` to be thrown by non-synced Realms, or that in the case of stable IDs `IncompatibleHistories` will be thrown when opening both synced and non-synced Realms? My understanding is that the former is true, but in the case of stable IDs it's only synced Realms that we'll see this with. Is that accurate?

**Comment by simonask** [comment]
`IncompatibleHistories` can be thrown at any time when someone is trying to open a Realm file with an unexpected history type. There is no such thing as a non-synced Realm with stable IDs, so the situation there is the same as today.

| On-Disk History Type | Opener Asking For | Result |
|---------------------|--------------------|--------|
| Non-Synced             | Non-Synced            | 👌  |
| Non-Synced             | Synced                     | `IncompatibleHistories` |
| Synced Pre-Stable IDs | Non-Synced        | `IncompatibleHistories` |
| Synced Pre-Stable IDs | Synced                | `IncompatibleHistories` |
| Synced with Stable IDs | Non-Synced       | `IncompatibleHistories` |
| Synced with Stable IDs | Synced               | 👌 |

The "client reset" in this case should happen only when opening a "Pre-Stable IDs" Realm in "Synced" mode. Unfortunately, the only indication that this is happening is the string message of the `IncompatibleHistories` exception. If you prefer, we can change the exception type in this case.

**Comment by bdash** [comment]
After looking in to this, I think there are two things we need to do:
1. Make it possible to distinguish between attempting to open a non-synced Realm as a synced Realm, and attempting to open a pre-stable ID synced Realm as a synced Realm with stable IDs. The former shouldn't trigger a reset, the latter should.
2. Rework the sequence of events in object store to ensure that we open the Realm before we create the sync session associated with that Realm. Currently we create the sync session first and then open the Realm, which often results in the sync session being the first path that sees the `IncompatibleHistories` exception. This exception ends up propagating out of `realm::sync::Client::run`, which makes it impossible to handle in a sensible fashion. Explicitly opening the Realm with the specified history type prior to creating the sync session would result in the exception being thrown in a much more manageable place. However, this may not be workable for clients that want to create a sync session directly, without interacting with it via an object store `Realm` instance. I'll need to do more research to determine whether that's a case we need to support.
