### ISSUE TITLE
Reject schema with nonoptional object property

### ISSUE THREAD

**Issue by kspangsege** [realm/realm-object-store#479]
Copied from https://github.com/realm/realm-js/issues/1104:

> Currently, all of the following properties (`alpha`, `beta`, and `gamma`) will be effectively optional:
> ~~~
> const Foo = {
>     name = 'Foo',
>     properties: {
>         alpha:  {type: 'Foo'},
>         beta:   {type: 'Foo', optional: false},
>         gamma:  {type: 'Foo', optional: true},
>     }
> };
> let realm = new Realm({schema: [Foo]});
> ~~~
>
> It seems to me that we should at least disallow `{type: 'Foo', optional: false}`, since it is ultimately not honored. I also think we should either disallow `{type: 'Foo'}`, or document that `optional` is true by default for object (link) properties.

**Comment by tgoyne** [comment]
[This is already done](https://github.com/realm/realm-object-store/blob/master/src/object_schema.cpp#L145).

**Comment by fealebenpae** [comment]
Right, JS actually overrides the user input in case the property is a link: https://github.com/realm/realm-js/blob/master/src/js_schema.hpp#L128.

Sorry @kspangsege, I’ll reopen https://github.com/realm/realm-js/issues/1104 and start tracking it.
