### ISSUE TITLE
No error reported when opening sync url with older ROS version

### ISSUE THREAD

**Issue by stel** [realm/realm-object-store#498]
When open realm URL with previous schema version get errors in console but `SyncManager`'s error handler is not called.

Errors I see trying open previously created realm with cocoa 3.0-beta:
```
2017-07-18 12:45:21.502190+0300 Realm Browser[14245:11539016] Sync: Connection[1]: Resolving 'localhost:9080'
2017-07-18 12:45:21.503741+0300 Realm Browser[14245:11539016] Sync: Connection[1]: Connecting to endpoint '::1:9080' (1/2)
2017-07-18 12:45:21.503882+0300 Realm Browser[14245:11539016] Sync: Connection[1]: Connected to endpoint '::1:9080' (from '::1:59909')
2017-07-18 12:45:21.508499+0300 Realm Browser[14245:11539016] Sync: Connection[1]: Writing failed: End of input
2017-07-18 12:45:21.508562+0300 Realm Browser[14245:11539016] Sync: Connection[1]: Connection closed due to error
```

@austinzheng, @bdash  is there a way to detect if realm you trying to open has an older schema format?

**Comment by bdash** [comment]
@stel clarified on the Cocoa meeting this morning that this occurs when attempting to connect to ROS 1.x from sync 2.x. This should definitely be raising an error at present.

**Comment by bdash** [comment]
It looks like the only error code we're receiving from sync is "end of input". I'd expect us to be receiving an explicit error about the server being too old.

**Comment by austinzheng** [comment]
We can't do anything about this, unfortunately. See https://github.com/realm/realm-cocoa/issues/5404 for a prior attempt.

**Comment by bdash** [comment]
@austinzheng, I'm not sure why this was closed. The entire point of https://github.com/realm/realm-sync/issues/1516 was to make it so sync returned a meaningful error in this case. Did that change not have the desired effect for some reason? If so, we should have sync take another shot at fixing it so we can expose a meaningful error.

**Comment by austinzheng** [comment]
Sure. Would it help sync if I built a simple Cocoa repro case?

**Comment by bdash** [comment]
I suspect it's possible to reproduce via the browser. If so, what I'd do to try and isolate the issue would be to determine if sync generates the correct error when connecting directly to a sync server (without ROS in the middle). If it does, we know that ROS is interfering with the fix from https://github.com/realm/realm-sync/issues/1516. If not, sync may need to take another crack at exposing the correct error code.
