### ISSUE TITLE
Object store should handle absence of metadata table in synced Realms without throwing exception

### ISSUE THREAD

**Issue by bdash** [realm/realm-object-store#502]
If a synced Realm pulls down user tables but not the object store's metadata table, we can end up calling `create_initial_tables` when most of the schema is already in place. If the schema doesn't match the schema in the file, this can lead to us attempting to make non-additive schema changes, leading to sync throwing an "unsupported instruction" exception.

The absence of the metadata table itself appears to be a bug (realm/realm-sync#1491), but the object store could be more resilient to the absence of the metadata table and not attempt to make non-additive schema changes when in additive schema mode.

/cc @tgoyne

**Comment by morten-krogh** [comment]
Is it enough for you to know the schema or do you also need to know the version it has?

If the schema is enough, it seems that the metadata table is unnecessary.

**Comment by bdash** [comment]
What we need to change is how we handle the transition from Realms without a schema version to having a schema version. Previously this would only occur in a newly-created Realm, in which case we want to make the schema in the Realm file match the schema provided by the app. Now, with sync v2.x, a Realm without a schema version could also be one that was downloaded by sync. In that case we need to ensure that we stick to performing only additive schema operations, rather than attempting to make the schema in the Realm match that provided by the app.

When in additive schema mode, the schema version is only necessary to determine whether indexes should be added or removed. This prevents two different clients that have different ideas as to which properties should be indexed from repeatedly adding and removing indexes. This should work fine when the schema version isn't synced, since each client will only add or remove indexes if its stored schema version was older than new schema version being used by the app (i.e., when the app developer makes a change to their app's schema).

**Comment by morten-krogh** [comment]
Search indexes are not being synced anymore in 2.0 as far as I remember, if that is what you mean
by repeatedly adding and removing indexes.

**Comment by bdash** [comment]
Can you provide some confirmation of that? I know t was discussed at one point, but I don’t recall that change being made.

**Comment by bdash** [comment]
Ok, it looks like that was done in realm/realm-sync#1330.
