### ISSUE TITLE
SyncFileManager::user_directory may assume wrong location of the Synced Realm

### ISSUE THREAD

**Issue by nhachicha** [realm/realm-object-store#515]
Most of the bindings offer the possibility to use a custom location where to store the Realm (or Synced Realm).

- [JS](https://realm.io/docs/javascript/1.10.0/api/Realm.html#.defaultPath)

- [Cocoa](https://github.com/realm/realm-cocoa/blob/9bbd27e7e899197bc986aabae17f1bcf9652fa81/Realm/RLMSyncConfiguration_Private.h#L34) _even though it's hidden_

- [.NET](https://realm.io/docs/xamarin/1.6.0/api/reference/Realms.RealmConfigurationBase.html#Realms_RealmConfigurationBase_DefaultRealmName)

- [Java](https://realm.io/docs/java/3.5.0/api/io/realm/SyncConfiguration.Builder.html#directory-java.io.File-)

However, the ObjectStore assume the location of the Realm under `SyncFileManager::user_directory` using `get_base_sync_directory()`. However, this assumption might not be true. 

_Example with Cocoa:_

Imagine if we use `syncConfiguration.customFileURL` to set a custom location. We still have the ObjectStore `user_directory` (used to work out the Realm path) pointing to the default one (`RLMDefaultDirectoryForBundleIdentifier`) since this call https://github.com/realm/realm-cocoa/blob/5e99e8feaf6ac2fa8614c8b2abeb3ab43580e4ee/Realm/RLMRealmConfiguration%2BSync.mm#L45-L46 will set the `rootDirectory` to the value of `RLMDefaultDirectoryForBundleIdentifier` (which might be different from `customFileURL`)

this will particularly break because the Realm will be created using the `customFileURL` but methods like `SyncManager::path_for_realm` or `SyncFileManager::remove_user_directory` will be acting upon the `get_base_sync_directory` (that suppose the Realm is under `RLMDefaultDirectoryForBundleIdentifier"/realm-object-server"`)

For now, there is no major side effect besides not being able to delete the Realm after a logout/client reset (since the `remove_user_directory` assume the wrong location) but it may have another side effect in the future.
cc @austinzheng

**Comment by austinzheng** [comment]
I don't know why it doesn't, but the file metadata really should be just storing the path outright. I think the reason it doesn't is because we lose the path information between the point where the Realm configuration is created and when the session is started.

**Comment by bmunkholm** [comment]
Outdated.
