### ISSUE TITLE
SIGSEGV when resolving ThreadSafeReference for deleted parent

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-object-store#528]
In .NET we have the following test that crashes with SIGSEGV:

```csharp
// obj.Dogs is a List<RealmObject>
var listReference = ThreadSafeReference.Create(obj.Dogs);
_realm.Write(() => _realm.Remove(obj));
await Task.Run(() =>
{
    using (var otherRealm = Realm.GetInstance(_realm.Config))
    {
        var otherList = otherRealm.ResolveReference(listReference);
        Assert.That(otherList, Is.Null);
    }
});
```

The crash seems to originate from a call to https://github.com/realm/realm-object-store/blob/master/src/list.cpp#L62 where `m_link_view.m_origin_column` is `nullptr`. Not entirely sure if it's an OS problem, but seems that the array of primitives changes have either exposed it or caused it. Also, I'm not if this is supported scenario or not - previously it has worked which is why we tested for it but in any case, we shouldn't crash.

**Comment by tgoyne** [comment]
This is supposed to work and we have tests for it, but of course the great part about UB is that it can "work" by coincidence. Wrapping that line in a check to see if the linkview is actually attached is probably the right fix here.
