### ISSUE TITLE
Change notifications for Array of Primitives report wrong indexes

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-object-store#541]
From @zaki50 :
```
Change listener to primitive list always report wrong index in `OrderedCollectionChangeSet`…
All insertions are reported at the tail of the list, all deletions are reported at the head of the list…
```

This was only reported on Slack. @zaki50 can chime in if he has an actual unit test for it.

**Comment by zaki50** [comment]
I made tests to reproduce this issue.

`add` is always reported as if it happened at the tail of the list.
https://github.com/realm/realm-java/pull/5213/commits/b4ff2e077b38bc041b1254e4f518018cec91ef5d#diff-bc81fd0bf97bab3845d36c382414eb42R1011

`replacing value` is never reported.
https://github.com/realm/realm-java/pull/5213/commits/b4ff2e077b38bc041b1254e4f518018cec91ef5d#diff-bc81fd0bf97bab3845d36c382414eb42R1059

`remove` is always reported as if it happened at the head of the list.
https://github.com/realm/realm-java/pull/5213/commits/b4ff2e077b38bc041b1254e4f518018cec91ef5d#diff-bc81fd0bf97bab3845d36c382414eb42R1109

**Comment by beeender** [comment]
This might be a bug in java side, i am checking now.

**Comment by nirinchev** [comment]
Is there anything special about your list (e.g. is ordering applied to it?), because .NET tests for notifications haven't uncovered issues, but it very well may be that we have missed some case.

**Comment by beeender** [comment]
For historical reason, `RealmList.addListener()` will add listener to a `Results` which is created from `List`/`LinkView`. And that doesn't work well with primitive arrays. 
Also there is another problem on the `LinkView` based `List`. I will create a test case later to show the problem.

**Comment by beeender** [comment]
The notifications work fine on `List`. there might be issues with notifications on primitive `Results`which is created from `List`. I will create a separate issue later.

**Comment by beeender** [comment]
Created https://github.com/realm/realm-object-store/pull/602
