### ISSUE TITLE
Adding null value to non-null field increases list length

### ISSUE THREAD

**Issue by zaki50** [realm/realm-object-store#544]
Adding null value to non-null list field throws an exception, but the length of the target list also increase. This happens only if the type of the list element is one of `String`, `Data` and `Date`.

I reproduced it in test in Java repository.
https://github.com/realm/realm-java/pull/5216/commits/787b1cc2414c793a890e0e0cca8c73909d0b2892

**Comment by beeender** [comment]
```
template<typename T>
void List::insert(size_t row_ndx, T value)
{
    verify_in_transaction();
    verify_valid_row(row_ndx, true);
    m_table->insert_empty_row(row_ndx);
    m_table->set(0, row_ndx, value);
}
```

The exception is thrown in the `Table::set()` where the empty row has been already inserted.

It seems we can throw it earlier since we could know the nullable status of the property:

```
template<typename Fn>
static auto switch_on_type(PropertyType type, Fn&& fn)
{
    using PT = PropertyType;
    bool is_optional = is_nullable(type);
    switch (type & ~PropertyType::Flags) {
        case PT::Int:    return is_optional ? fn((util::Optional<int64_t>*)0) : fn((int64_t*)0);
        case PT::Bool:   return is_optional ? fn((util::Optional<bool>*)0)    : fn((bool*)0);
        case PT::Float:  return is_optional ? fn((util::Optional<float>*)0)   : fn((float*)0);
        case PT::Double: return is_optional ? fn((util::Optional<double>*)0)  : fn((double*)0);
        case PT::String: return fn((StringData*)0);
        case PT::Data:   return fn((BinaryData*)0);
        case PT::Date:   return fn((Timestamp*)0);
        case PT::Object: return fn((RowExpr*)0);
        default: REALM_COMPILER_HINT_UNREACHABLE();
    }
}
```

Shall we have the `Optional` version `unbox` for `StringData`/`BinaryData`/`TimeStamp` like:
```
inline Optional<StringData> JavaAccessorContext::unbox(util::Any& v, bool, bool) const
```

@tgoyne

**Comment by tgoyne** [comment]
The problem with `Optional<StringData>` is that `StringData` already can represent null. Cocoa and JS deal with this by doing the validation before passing the value to the object store rather than in `unbox()`, which ended up being basically the same amount of code and being necessary for producing good error messages anyway (since `unbox()` doesn't know things like the name of the property that the value is going to be stored in).

**Comment by beeender** [comment]
OK then. I think java can do the same, checking value before ubox to produce a better error message.
