### ISSUE TITLE
Add the ability to force a SyncSession reconnect to a different endpoint

### ISSUE THREAD

**Issue by alebsack** [realm/realm-object-store#563]
In ROS, using realm-js, we need to be able to reconfigure the location of a Realm while the session is open.  

It was previously discussed that it would be nice to be able to just change the URL on an existing session, but that may have larger implications with the internal state machine in object store.

Another proposal is to add an optional `resolver` callback to the Sync configuration, which is called when opening or reopening a connection to a sync server.  The resolver callback, when invoked with the original URL by the binding, should return a (in JS terms) Promise that will resolve the host part of the URL to an IP address and port. This IP address and port should then be used by the sync session to (re)open the underlying connection.

This way, the underlying session and URL never change, only the actual destination of the connection.

//cc @bigfish24 @bdash

**Comment by bigfish24** [comment]
@bdash will add that we discussed using the sync proxy, but turns out that isn't ideal since the proxy itself needs access to a synced Realm... which could failover. As such we thought this might be a less invasive change to make that would solve this issue. @kvap said he was going to explore it initially since it might involve realm-sync.

**Comment by kvap** [comment]
The intended usage in ROS would be:
```javascript
function obtainUrl(callback) {
    // Do some async stuff
    // to obtain the URL
    // and finally
    callback(url); // Callback is provided by `realm-sync` client
}

r = new Realm({
    sync: {
        user: myUser,
        url: obtainUrl, // function instead of string
    },
});
```

Looks like it will require:
- small changes in `realm-object-store` (new entry in sync config, passing the callback from the config to `realm-sync` connection config, similar to how `ssl_verify_callback` works)
- small changes in `realm-sync` (calling that callback)
- a bit bigger changes in `realm-js` (glue JS and C++, schedule on proper threads)

cc @bdash @morten-krogh

**Comment by bdash** [comment]
I think it’d be necessary for the binding to have a separate field in the sync config for this purpose, rather than overloading the URL field. This is because object store still needs to use the URL to determine where the synced Realm should be stored on disk.

**Comment by alebsack** [comment]
@bdash that was my thought as well...
```
r = new Realm({
    sync: {
        user: myUser,
        url: "realm://default/mypath",
        resolver: async (url) => {
            return "127.0.0.1:7894";
        }
    },
});
```

**Comment by kvap** [comment]
The binding can call the obtainer function to populate the url field in sync config before passing it to object store. Or we can put the function in a separate field, as @alebsack proposed, does not matter much.

**Comment by bdash** [comment]
Calling the resolver function wouldn't be sufficient. You'd want the URL field to have the same value independent of what the resolver returns, otherwise you'd end up using different on-disk Realms from run to run depending on what the resolver happened to return on its first call.

**Comment by alebsack** [comment]
@bdash correct, the url provided above would not change internally, keeping the local path to the realm constant.

**Comment by morten-krogh** [comment]
Why does it have to be a callback instead of a session method?

If you don't like a mutable url, just call the method, set_server_address() for instance.
Whenever set_server_address() is called, the sync client disconnects if needed and connects to the new address.

**Comment by morten-krogh** [comment]
Actually, I think the rationale for changing sync is very weak. 
Why can't Object store destroy the sync session and create a new sync session but keep the 
same object store session?
Object store's notion of a session could be something else than sync's notion of a session.
Session is just a word.

**Comment by kvap** [comment]
Destroying and creating the sync session will require resetting all the error/progress/etc callbacks and other stuff, which will be complex and brittle.

**Comment by morten-krogh** [comment]
You will set them to the same as before. Is that brittle?

**Comment by morten-krogh** [comment]
What about a method instead of a callback?

**Comment by kvap** [comment]
A method sounds like a simpler solution.

**Comment by kvap** [comment]
@bdash would it be fine if I added a method like `SyncSession::override_server(std::string address, int port)` which sets the address and port overrides and then destroys/creates the session (if it has been bound)?

**Comment by bdash** [comment]
I don't see how we can keep progress notifications and upload / download completion handlers working correctly given such an API. That's where the motivation to push this down to the sync level comes from.

**Comment by bigfish24** [comment]
@bdash quick update after sprint planning. @kvap is wrapping up the sync change and might need you to take over to propagate up depending on how far he gets.
