### ISSUE TITLE
Prevent addition of 2nd `/__partial/...` suffix to Realm path as a result of `partial: true`

### ISSUE THREAD

**Issue by kspangsege** [realm/realm-object-store#579]
Currently, if one specifies a sync URL with a path that explicitly contains the `__partial/<unique ident>` suffix, and then also enables partial sync through `partial` property on sync config object, then the path that is sent to the server, will end up containing the substring `/__partial/` twice.

This pushes the server into undefined territory, and can easily lead to a server-side crash.

The right solution seems to be, to prevent object store from adding the partial suffix to a path that already has a partial suffix.

From the point of view of the server, a path has a partial suffix if, and only if the path matches the regular expression, `/__partial/[^/]*$`.

In my opinion, and for extra safety, we should actually go one step further, and disallow the partial suffix on any application specified sync URL path, regardless of whether `partial: true` is specified or not. A consequence of this, of course, is that it will no longer be possible to bypass the partial sync API, but I think that is the desirable, as it also prevents accidental activation of partial sync mode.

cc @bdash 

For some context, see https://github.com/realm/ros/issues/529#issuecomment-336603233.

**Comment by austinzheng** [comment]
I prefer the option where we completely reject paths containing the string `__partial`. We may want to go one step further and simply reject any path with a component prefixed by `__`, so we can use those in the future.

**Comment by kspangsege** [comment]
@austinzheng Sounds good to me.

**Comment by bdash** [comment]
I don't think we can reject anything leading with `__` since we need to allowing opening internal ROS Realms that also follow that convention.

**Comment by austinzheng** [comment]
Will we ever need bindings to explicitly open those internal ROS Realms, versus opening them within object store and exposing APIs to work with them (like what we've done for permissions)?

**Comment by bdash** [comment]
The bindings currently open some of those Realms directly, and ROS does also.
