### ISSUE TITLE
register_progress_notifier and is_streaming = false

### ISSUE THREAD

**Issue by beeender** [realm/realm-object-store#581]
The problem:
`SyncSession::register_progress_notifier` is disconnected from the Realm version on the thread, which makes it somehow useless in the real life and feels buggy.

Example:
```
// on thread A
Realm realm = getInstance(config); // Group version 1
writeData(realm); // WriteA GroupVersion -> 2
writeData(realm); // WriteB GroupVersion -> 3
realm.close();
SyncSession session = SyncManager.getSession(config);
session.register_progress_notifier(callback, upload, false);
```

The `callback` in above code actually might be called in various conditions
1. The callback is called after all the data after `WriteB` get uploaded to the server. And then callback won't be triggered anymore. This is what I expected as a user, since before adding the callback, everything i have committed locally already. I probably want to show a progress bar to say that everything has just be synchronized to the server.  In this case, the `snapshot_version` passed from sync should be `>= 3`.

2. The callback is called with after all data in `WriteA` has been uploaded, but not in `WriteB`. Here the `snapshot_version` should be `== 2`

3. The callback is called with no data committed by user. This could happen if the Realm file was first time created, and sync only uploaded the meta data to the server. `snapshot_version == 0`. Quite similar to 2), but still, it is not user expected.

With current ObjectStore implementation, all above could happen. 

Maybe we can solve it by:
```c++
uint64_t SyncSession::register_progress_notifier(std::function<SyncProgressNotifierCallback> notifier,
                                                 NotifierType direction, bool is_streaming, int64_t expected_version)
{
    auto wrapped_progress_handler = [this, weak_self](uint_fast64_t downloaded, uint_fast64_t downloadable,
                                                  uint_fast64_t uploaded, uint_fast64_t uploadable,
                                                  bool is_fresh, uint_fast64_t snapshot_version) {
        if (auto self = weak_self.lock() && snapshot_version >= expected_version) {
            handle_progress_update(downloaded, downloadable, uploaded, uploadable, is_fresh);
        }
    };
}
```

So bindings need to change the public API as well to decide which version of data is user want to see the progress from.

The `uploaded` and `uploadable` might be less than what user expected, but i guess it is an issue has to be solved in the sync side and it is kind of minor.

thoughts? @cmelchior @austinzheng @morten-krogh

**Comment by beeender** [comment]
also the `wrapped_progress_handler` doesn't match the signature of sync's `ProgressHandler`

```
    using ProgressHandler = void(std::uint_fast64_t downloaded_bytes,
                                 std::uint_fast64_t downloadable_bytes,
                                 std::uint_fast64_t uploaded_bytes,
                                 std::uint_fast64_t uploadable_bytes,
                                 std::uint_fast64_t progress_version,
                                 std::uint_fast64_t snapshot_version);

```
    auto wrapped_progress_handler = [this, weak_self](uint_fast64_t downloaded, uint_fast64_t downloadable,
                                                      uint_fast64_t uploaded, uint_fast64_t uploadable,
                                                      bool is_fresh, uint_fast64_t /*snapshot_version*/) {
```

The `is_fresh` is `bool` but it should be `std::uint_fast64_t` ?

**Comment by beeender** [comment]
Similar issue for downloading progress actually, but the problem for downloading is user cannot have a certain expectation of what should be downloaded.

**Comment by cmelchior** [comment]
Exposing the concept of versions in the public API is something I would really like to avoid. Generally, we should just use whatever snapshot version that is the latest at the time of registering the listener IMO. How to make that happen is another thing though.

**Comment by morten-krogh** [comment]
First regarding 
"The is_fresh is bool but it should be std::uint_fast64_t ?"
In sync, it is an integer because I anticipated an extension where the client could send "mark" messages" and bump the is_fresh number. At the moment, it is just 0 or 1, and can be represented by a boolean. 1 means that there has been contact with the server, and 0 that there has not.
If you see downloadable = 0, for example, you cane see from is_fresh, whether is just the local cache that says downloadable = 0, or whether the server has said it in the current session.

Anyway, this is not the issue here. Just a side remark.

**Comment by morten-krogh** [comment]
The parameter snapshot_version was introduced for exactly your use case.

**Comment by morten-krogh** [comment]
From sync's point of view, it doesn't matter whether the checks are done in object store or in the binding.

Let us say that you commit a write transaction.
version = realm.commit();
Say version = 3.

To be sure that you have uploaded everything in your transaction (and earlier), you can track the
progress callbacks and perform some checks.

The simpler check is this:

callback_snapshot_version >= 3 and uploaded_bytes == uploadable_bytes.

The more advanced, and slightly better check is this:

The first time you get a callback with 

callback_snapshot_version >= 3, you remember uploadable_bytes from that callback.
The in the same callback and all further callbacks you wait for

uploaded_bytes >= remembered_uploadable_bytes.


The advantage of the advanced check is that it will terminate earlier. Imagine a situation
where you keep making new write transactions and uploaded_bytes is always below uploadable_bytes.

**Comment by nirinchev** [comment]
I'm not sure I understand case 2. Is the callback called after A has been uploaded and then not triggered anymore or is it called multiple times?

**Comment by morten-krogh** [comment]
@beeender What did you mean by

"The uploaded and uploadable might be less than what user expected, but i guess it is an issue has to be solved in the sync side and it is kind of minor."

**Comment by beeender** [comment]
@nirinchev 
> I'm not sure I understand case 2. Is the callback called after A has been uploaded and then not triggered anymore or is it called multiple times?

Sorry for the confusion. I mean the use case 1 is actually user wants always. The 2) and 3) are more like bug from user point of view.

@morten-krogh 
> Did you mean because the snapshot_version was ignored. In that case yes, but the solution is to use it.

Yeah, the problem is the `SharedGroup` version is kind of thing that most users are not familiar with. We need to educate user about that. The user will just be confused after a commit, the callback says 100% has been uploaded, but it doesn't happen.
So the problem becomes that how would be design the public API of binding. It could be one of those:

1. 
```
Version version = realm.commitTransaction();
session.addProgressListener(UploadType, callback);
typedef void(uploaded_bytes, uploadable_bytes, snapshot_version) ProgressCallback;
```

2.
```
Version version = realm.commitTransaction();
session.addProgressListener(UploadType, callback, version);
typedef void(uploaded_bytes, uploadable_bytes) ProgressCallback;
```
in this way if we filter all snapshot version (`<version`) notification. then the `uploadable_bytes` might be less than it actually uploaded from the time when the callback was registered i think? Uh, re-think of this, this might not be possible since by filtering out all `snopshot_version < version`, then the callback will only be triggered after all the expected data uploaded.

I guess the option 1 is the only possible way to implement right now. And user has to know the concept of Realm's data version.

**Comment by morten-krogh** [comment]
The callback can be triggered before everything is uploaded. You have to check the values. Just to make sure you know this.

You could also store the version of the last transaction internally in object store or the bindings.
Then the user would not need to supply the version number.

So, at

realm.commitTransaction(), you remember the version without involving the user.
At 
session.addProgressListener, you use the store version internally.

Do you understand what I mean. You can have a middle layer between the user and the lower level callback.

**Comment by nirinchev** [comment]
> Sorry for the confusion. I mean the use case 1 is actually user wants always. The 2) and 3) are more like bug from user point of view.

Yes, I understood that, but not sure I understand the problem with case 2. When it happens, what are the values of `uploaded_bytes` and `uploadable_bytes`?

**Comment by beeender** [comment]
@nirinchev 
when case 2 happens, the `uploadable_bytes` could be the size of data created in `WriteA`. And the size of data created in `WriteB` is not included.

@morten-krogh 
> realm.commitTransaction(), you remember the version without involving the user.
>Do you understand what I mean. You can have a middle layer between the user and the lower level callback.

Yes, i totally understand that. The problem user doesn't need a opened Realm instance to call `SyncSession.addProgressListener()` which means we have no idea which version to remember. 
The public API has to be changed to involve either a `SharedRealm` instance or a `Version` directly.

**Comment by morten-krogh** [comment]
Would it work to look in the Realm?
 After all, you could make a dummy read transaction.

**Comment by morten-krogh** [comment]
Also, I think it is a powerful API to let the users know about versions. 
The users could make fine grained requests for upload completion and handle it themselves.
But maybe it goes against the simplicity of Realm.

**Comment by nirinchev** [comment]
I think exposing versions is giving people too fine-grained control and will be very confusing. In .NET and js we expose the GetSession method on the Realm, while Java has opted for a sync manager and cocoa - for a user. Probably we should align there in a way that allows us to fix this issue without having to explain yet another topic to people.

**Comment by beeender** [comment]
By not exposing the db version actually make our current API very much useless. Here is what I found for issue https://github.com/realm/realm-sync/issues/1770

Here is the helper function to upload some data to server and wait until the data fully uploaded by register a uploading progress callback.

```java
    // Create remote data for a given user.
    private URI createRemoteData(final SyncConfiguration config) {
        final Realm realm = Realm.getInstance(config);
        final CountDownLatch changesUploaded = new CountDownLatch(1);
        final SyncSession session = SyncManager.getSession(config);
        final long beforeAdd = realm.where(AllTypes.class).count();
        writeSampleData(realm);

        session.addUploadProgressListener(ProgressMode.INDEFINITELY, new ProgressListener() {
            @Override
            public void onChange(Progress progress) {
                if (progress.isTransferComplete()) {
                    Realm realm = Realm.getInstance(config);
                    final long afterAdd = realm.where(AllTypes.class).count();
                    realm.close();

                    RealmLog.warn(String.format(Locale.ENGLISH,"createRemoteData upload %d/%d objects count:%d",
                            progress.getTransferredBytes(), progress.getTransferableBytes(), afterAdd));
                    // FIXME: Remove this after https://github.com/realm/realm-object-store/issues/581
                    if (afterAdd == TEST_SIZE + beforeAdd) {
                        session.removeProgressListener(this);
                        changesUploaded.countDown();
                    } else if (afterAdd < TEST_SIZE + beforeAdd) {
                        fail("The added objects are more than expected.");
                    }
                }
            }
        });
        TestHelper.awaitOrFail(changesUploaded);
        realm.close();
        return config.getServerUrl();
    }
```

In this function we try to identify the uploading is finished by two conditions:
1. Check if the newly created data exists in the Realm on the callback thread.
2. Check if uploadable == uploaded

This works if the callback is called on the sync client thread.
But actually there is a chance the callback gets called immediately after registered because of some other data created before just got uploaded. In this case, the data does exist in the Realm on the caller thread (we just add on the same thread), and the uploaded could equal to the uploadable.

So I don't see there is any chance we don't expose the details of db version to users. IMO creating any other concept than the db version in bindings will just make more confusion to users. Plus it is absolutely a good thing to let user know there is a **version** concept in Realm since they keep seeing the db not up-to-date, db size keeps growing which all related to the db versions. Users have to know every committed transaction creates a new version in Realm. Hiding the concept doesn't make too much sense.

PS. to fix the above function this works:

```java
        final long threadId = Thread.currentThread().getId();

        session.addUploadProgressListener(ProgressMode.INDEFINITELY, new ProgressListener() {
            @Override
            public void onChange(Progress progress) {
                if (threadId == Thread.currentThread().getId()) {
                    return;
                }
            // ....
            }
```

By only accept the `if (threadId == Thread.currentThread().getId()) ` on the sync client thread will make sure the data has been uploaded.

Also, the progress callback could be called on a random thread in java (the caller thread or the sync client thread) might be another problem, but it is another topic.

**Comment by cmelchior** [comment]
I agree with @nirinchev ... Exposing the Realm version to users as a concept is way to complicated.

If I'm not mistaken, we should be able to switch the version-based API without users knowing about it, i.e. when the callback is registered we use the version of the _latest_ version.

This causes a race condition when using CHANGES_ONLY. E.g consider the following the code:

```
write_to_realm();
<-- Another write could happen here
register_listener();
```
But at worst, by using the latest version number, when the listener is triggered, the data you care about _have_ been uploaded, and maybe a little more, but that should be harmless.

This is also what Morten writes here: https://github.com/realm/realm-object-store/issues/581#issuecomment-337608147

I'm not sure if storing the version number is possible in OS though since capturing writes from other processes might be difficult?

**Comment by beeender** [comment]
```
write_to_realm();
<-- Another write could happen here
register_listener();
```

This is not practical ...
First thing is `register_listener` needs a session but not a Realm instance. So when it gets called, all the instances on that thread could have been closed already. Then we don't really have a way to get a version number which user wants.

 Consider that we support async transaction in java:

```
realm.executeTransactionAsync(...);

// So anything we can do here to know a version number which user wants?
register_listener();
```

There is a conflicts of the `Realm` and `SyncSession` in our API design. Realm instance has different states on different threads, but `SyncSession` doesn't. Which means all APIs of `SyncSession` should be stateless. But clearly this one is not -- it is stateless right now, but it is also useless for users since user doesn't know what does the progress mean.

**Comment by austinzheng** [comment]
I agree that the way this API is exposed to bindings should be re-thought. Unfortunately, some of the limitations seem to be difficult to work around.

Like Mulong said, `SyncSession` isn't tied to any specific instance of a Realm that a user opens from a binding API. Instead, all of its operations are relative to the Realm instance opened by the sync layer itself (through the `sync::Session`). So it's not really useful right now to observe the state of any specific, e.g. `RLMRealm` instance that a user might have created to represent a synchronized Realm.

If we wanted to expose version numbers we'd have to do it not only for `SyncSession`'s APIs, but also for Realm instances as well. If we don't want to expose version numbers we'd need to figure out a way to convey this information to our APIs, for example an API to observe progress that takes in a Realm instance to know what version to watch for, or a `write` API that registers an observation block at the same time.

If someone wants to take up the role of feature lead and design a revised binding API which they want object store to support, I can make the required object store changes. It seems there's already been quite a bit of discussion and ideas so far, so there is probably someone who knows what they want better than I would.

**Comment by cmelchior** [comment]
I'm not sure I see a problem in caching the latest Realm somewhere in a static variable that can be accessed no matter if there are open Realm instances are not. Progress listeners do not care about possible extra versions of other processes so there shouldn't be any interprocess problems? 

i.e you cache the version when:
1) Open the SharedGroup
2) Commit a transaction

**Comment by Zhuinden** [comment]
@cmelchior 

> I'm not sure I see a problem in caching the latest Realm somewhere in a static variable that can be accessed no matter if there are open Realm instances are not. 

What thread would be able to access that Realm, how will it receive updates, and who'll be able to close it?

**Comment by cmelchior** [comment]
Sorry, I meant `Realm version`. I updated the comment

**Comment by morten-krogh** [comment]
If nothing else, you can always make a new read transaction in the Realm to get version.
That version might be too high, but that is only a slight nuisance. 
For upload completion, you want the guarantee that some specific data is uploaded. It is okay if the 
completion is conservative.

Caching the latest version avoids the read transaction, but is similar otherwise.

Wouldn't it be possible for you to have the latest version of a write transaction stored in a particular
thread confined Realm object. When the user performs wait_for_upload_completion_of_latest_write_by_this_instance, you use that number.

There could also be a global wait_for_upload_completion_of_everything, that would use the highest known version number.

**Comment by tgoyne** [comment]
I think this is fixed by https://github.com/realm/realm-object-store/pull/624, but the above discussion makes this sound much more complicated and I don't really follow it.
