### ISSUE TITLE
Remove support for building Sync 1.*

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-object-store#586]
Would enable us to remove a bunch of ifdefs + duplicated `dependencies.list` files

**Comment by bdash** [comment]
We should do this at some point, but it hasn't been that challenging to support both versions so I don't think we need to rush into this.

**Comment by Zhuinden** [comment]
Wasn't this done in https://github.com/realm/realm-object-store/commit/de5a81420ee255b83bc6488aee80fc36392e8387 ?

**Comment by bdash** [comment]
Yes, this was done in #616.
