### ISSUE TITLE
Performance regression in sorted query accessors since results integration

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-object-store#598]
From https://github.com/realm/realm-java/issues/5328

Since Realm-Java 3.0, the following query

``` java
        Schedule schedule = query(realm)
                .lessThanOrEqualTo(ScheduleFields.START_TIME, date)
                .equalTo(ScheduleFields.CHANNEL_ID, channel.getId())
                .findAllSorted(ScheduleFields.START_TIME, Sort.DESCENDING)
                .first(null); // 
```

is significantly slower than in Realm-Java 2.3.0 or before. `first` is already the optimized version, previously using `size()` and `get(0)` froze the UI on scroll.

The change was that Realm Object Store's `results` was integrated, which is quite a big change...

But this is not insignificant compared to previous core behavior, so it's worth looking into. Size and get shouldn't be slow!

**Comment by bdash** [comment]
Someone from @realm/java will need to weigh in on what object store methods this ends up calling vs what core methods it called in earlier versions.

**Comment by Zhuinden** [comment]
Might have been fixed by https://github.com/realm/realm-java/pull/5556
