### ISSUE TITLE
Trigger notifications immediatley for Results

### ISSUE THREAD

**Issue by beeender** [realm/realm-object-store#605]
This is related with #604 

The use case in Java:

We support a method `RealmQuery.load()` (the API was added before using OS notifications) to run the async queries immediately if it has not been executed before, and trigger the callback with an empty changeset (since it is the first time async query returns) if needed.

It works with sequences like below

1. Create Results and register notification callback
2. `RealmQuery.load()` called, run `evaluate_query_if_needed(true)` to create the table view
3. call java callback with an empty changest and set `isLoaded` flag in java.
4. async query finished in bg thread
5. callback delivered to the caller thread, since the `isLoaded` is true, ignore this empty changeset notification.
6. Another change made by some other thread.
7. callback delivered to the caller thread with a non-empty changeset, java notify the user with the given changeset.

But it doesn't work as expected if there is a changed made by the other thread in step 2. Then the notification will be delivered by OS at the first time with an empty changeset, but at that time OS assume it is the first time caller using the `Results`.

It might also be a common problem for cocoa as well, like:

1. UI gets a Results
2. Instead of waiting for the callback, user manually refreshes the UI which means the `evaluate_query_if_needed()` was called through results's accessors.
3. at the meanwhile a change is made on the other thread.
4. UI gets an notification with an empty changeset so it has to refresh the whole list view. (But if the changeset should only include the changes in step 3. )

```
    SECTION("test")
    {
        CollectionChangeSet change;
        size_t notification_calls = 0;
        auto token = results.add_notification_callback([&](CollectionChangeSet c, std::exception_ptr) {
            notification_calls++;
            change = c;
        });

        results.evaluate_query_if_needed(true); // Shouldn't this trigger notification?

        r2->begin_transaction();
        size_t ndx = r2_table->add_empty_row();
        r2_table->set_int(0, ndx, 5);
        r2->commit_transaction();

        advance_and_notify(*r);
        REQUIRE(notification_calls == 2);
        REQUIRE_INDICES(change.insertions, ndx);
    }

```

@tgoyne Any suggestions?

**Comment by cmelchior** [comment]
@tgoyne Did you have any chance to look at this?

**Comment by tgoyne** [comment]
Blocking the UI thread to wait for the background worker to be fully initialized is very unlikely to ever be a net benefit over reloading the UI one extra time, and that's what would be required to synchronously send an initial notification and then provide changes from that. Synchronously sending the initial notification and then sometimes sending a *second* initial notification would not require blocking the UI thread, but I don't know what the point of that would be.

**Comment by bmunkholm** [comment]
Ping @cmelchior @tgoyne Trying to cleanup Triage - what should happen with this?
