### ISSUE TITLE
Wrong error message when schema version incorrect

### ISSUE THREAD

**Issue by icanzilb** [realm/realm-object-store#625]
The arguments for the old and new schema versions are swapped when formatting the error message here: 

https://github.com/realm/realm-object-store/blob/21e671a155989f4e34e279fc8a7ace5817495de0/src/object_store.cpp#L897

```cpp
logic_error(util::format("Provided schema version %1 is less than last set version %2.", new_version, old_version))
, m_old_version(old_version), m_new_version(new_version)
```

This leads to a confusing (and untrue) error message like the following: 

```
Provided schema version 1 is less than last set version 0
```

Tested with RealmSwift 3.1.0 / Xcode 9

**Comment by bmunkholm** [comment]
The order actually looks correct to me. But I can see it's also being called in another situation where the versions are expected to be identical:

case SchemaMode::Immutable:
            if (version != m_schema_version)
                throw InvalidSchemaVersionException(m_schema_version, version);

**Comment by icanzilb** [comment]
I don't really know what parameters order `logic_error` expects, they just seemed swapped to me at first sight. In any case, the error message saying `1 is less than 0` did happen to me while working on an iOS app and it's what made looked into the source
