### ISSUE TITLE
Report unique device ID to ROS in HTTP header

### ISSUE THREAD

**Issue by bmunkholm** [realm/realm-object-store#646]
See realm/raas#817. 
We need to send a unique device ID in the HTTP header or token to support reporting of devices in ROS. As unique as the platform allows. It's ok it's not uniques across app installs.
For iOS we can use UIDevice.current.identifierForVendor!.uuidString
For Android and JS I assume there is something equivalent?

**Comment by nirinchev** [comment]
I don't think we should try to use a os-specific uuid retrieval as that will be too involved to implement on the other platforms we support - Windows, Linux, etc. Instead, OS should generate a uuid and persist it somewhere.

**Comment by astigsen** [comment]
Where is the client_uuid stored?

**Comment by bdash** [comment]
In the metadata Realm within the application's data directory.

**Comment by bmunkholm** [comment]
@nirinchev Where would we persist that (independent of any specific realm)? Don't we just swap the problem of the platform specific ID with platform specific persistence?

**Comment by bmunkholm** [comment]
Not needed anymore due to new pricing.
