### ISSUE TITLE
Adapt handling of listening on changes in multiple tables

### ISSUE THREAD

**Issue by finnschiermer** [realm/realm-object-store#678]
Core 6.0 has changed it's use of version counters on tables. Adaptation is needed in OS.

With pre-6.0 Core, the version counter on a table would reflect changes in any table reachable through link or backlink from said table.

With Core 6.0, this is changed so the version counter on a table reflects only changes to that table.
Consequently, Queries/TableViews now track multiple tables where necessary.

OS provides to bindings the option of registering a listener on a table. With pre-6.0 this listener reflects the version counter and is thus called on any change on an object reachable from said table - even if the table itself is unchanged. As the meaning of the version counter changes with 6.0, OS will need to track versions for multiple tables, to preserve the semantics visible to the app developer.

Exactly which tables to track can be derived from the schema.

The relevant counter to monitor on each table is available as Table::get_content_version().

**Comment by tgoyne** [comment]
I think the only ObjectStore thing which needs to change is ResultsNotifier, which uses the version info from Query to decide if it needs to run. It already traverses the schema to find out what tables it needs to care about (see `DeepChangeChecker::find_related_tables()` and the code which calls that), so I think all that needs to change is that it needs to use that information to sometimes perform the deep changeset calculation even if the query doesn't need to be rerun.

**Comment by jedelbo** [comment]
I am not really sure that anything need to change. I can see that ResultsNotifier already uses an array of table versions to check against.
@tgoyne In what cases do you think that it need to call `calculate_changes` in spite the query does not need to be rerun?

**Comment by jedelbo** [comment]
I have figured out what is wrong.

**Comment by jedelbo** [comment]
Fixed
