### ISSUE TITLE
Remove or Obfuscate ROS related files on mobile client side

### ISSUE THREAD

**Issue by ianpward** [realm/realm-object-store#680]
Encrypt all the files for Realm on the device (vs just the ‘.realm’ file), including the files in ROS related folders. Especially since there is text doc that has the userID(s) and the full ROS-URL address. 

![image](https://user-images.githubusercontent.com/1691481/43738068-46c7d2a0-9978-11e8-99ea-8d351d4430a3.png)

that file appears to be part of the migration logic from a very old version of sync and is no longer used for anything, so we just shouldn't be creating it at all

https://realmio.slack.com/archives/CA3J67WGH/p1533268863000200

**Comment by fealebenpae** [comment]
The realm files are already encrypted by default on Cocoa and Java, AFAIK, so all that's needed is to hash the filenames.

**Comment by roberhofer** [comment]
I can't figure out based on this conversation whether #681 closes this issue or not (?).

**Comment by ianpward** [comment]
Probably - ask @tgoyne when he returns
