### ISSUE TITLE
Core6: cache_new_schema refactor throwing a logic_error

### ISSUE THREAD

**Issue by nhachicha** [realm/realm-object-store#685]
The current implementation of commit in Java calls `shared_realm->commit_transaction();` this will call `m_coordinator->commit_write(*this);` which triggers any registered listeners, say we close the Realm inside the listener, then the OS calls `cache_new_schema();` which in the [new Core6 porting](https://github.com/realm/realm-object-store/blob/core-6/src/shared_realm.cpp#L428) calls `transaction()` -> `read_group()`  then calls `verify_open()` which  fails obviously since the Realm was closed.

The old implementation of  `Realm::cache_new_schema()` simply guarded against this use case by checking at the beginning if the shared_realm is still valid

```C++
if (!m_shared_group)
        return;
```

Note: The point was discussed with @tgoyne and he think this behaviour (relying on transaction needs a refactor)
>Thomas Goyne
`transaction()` is an incorrect hack and nearly everything that uses it is broken in some degree due to it not actually having the same semantics as what it replaced
... I need to change a lot of things related to it eventually

@jedelbo can you look at this while Thomas is off ?

**Comment by jedelbo** [comment]
If Thomas thinks this needs a bigger overhaul, then there is nothing I can do.

**Comment by nhachicha** [comment]
No longer reproducible, could be fixed by https://github.com/realm/realm-object-store/pull/811
