### ISSUE TITLE
make_dir() failed: File name too long (let's hash the server URL)

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-object-store#686]
My Mac has a total path length limitation of 300 chars (I read that its higher on other Macs - I don't know why its that low on mine ... **UPDATE: see [Simons comment](https://github.com/realm/realm-object-store/issues/686#issuecomment-413483490) 👇** ) and most windows machines has a path length limitation of 260 chars.

Query-based sync generates realms with very long "virtual paths" on the server, I have issues syncing these realms to my Mac or a Windows machine, specifically creating the `.management` directory fails when synchronizing with the Realm: https://github.com/realm/realm-studio/issues/793#issuecomment-412876054

> `Unable to open a realm at path '/Users/kraenhansen/Library/Application Support/Realm Studio/renderer-73853/realm-object-server/6347a228-8ec3-4a2f-8c66-b54b83ca8dd3/realms%3A%2F%2Fgorgeous-rubber-hat.us1a.cloud.realm.io%2Ftonyixhjaaavggucolzihusbnibdswrtkhvfflhzedizmrxkhpbwmcsfwbcutawnkomwfouhjqevtyedzghhgxyqqqzdfnbchlcwcsnogpmjqmddgxrjbrmjuwvujpoyeyugnoppoqqejwhqgogoshkkzezjayfhuicyhscqrwskhzflhoviigybwopldifhjvdwvxfudnxnikxpdapvwefuyddkjchksxlqbksnfnolaextqvhxindlcwrfjrqjezqi.management': make_dir() failed: File name too long.`

I suggest computing a hash of the server hostname, port and the realm virtual path instead of using a URL encoded version of this, when storing the file.

**Comment by ironage** [comment]
Using a hash would decrease the file name length, but it does not remove the limitation entirely. We could still have users run into this if they have long directory prefixes. Still, a hash may be the most practical solution and if we choose to go this way, we need to handle hash collisions intelligently.

**Comment by kraenhansen** [comment]
As far as I know the "directory prefix" is currently my CWD appended with "/realm-object-server", right? If the hash is a fixed length a developer would at least be able to reason about the length of paths created by the object store:

    length(CWD + "/realm-object-server/" + hash + ".management/access_control.pick_writer.cv")

As for "handling hash collisions intelligently" should that really be a concern? How many realms do we expect the (worse than average) client to be downloading and syncing against? As a first iteration, we could store the inputs for the hash in the realm (perhaps they are already there?), read them when opening the Realm and throw if they don't match what we expect, this would prevent data corruption and allow us to understand if this should be a real concern or not.

Another thought - could we decrease the risk of "long directory prefixes" by allowing users to specify the path in which synced Realms are stored? This would also help clean up Studio code (as it currently needs to change working directory to avoid conflicts from multiple sync agents from separate processes - it would be cleaner to tell Realm JS to store server Realms in a different directory if the Realm has already been opened in another browser).

**Comment by simonask** [comment]
What you're hitting is the limitation on macOS of individual directory/filename lengths of 255 characters, not the total path length (which is 1024). The name of the directory that we try to create here is 328.

The solution is probably the same. :)

I'm not sure where that really long name comes from exactly, but it might be possible to split things into subdirectories and avoid hashing (which would obscure what realm files correspond to which URLs).

**Comment by nirinchev** [comment]
Splitting it up won't help on Windows though, so let's try to find a solution that will fix both problems.

**Comment by simonask** [comment]
True point.

**Comment by ironage** [comment]
Hashing the file names will also help with obfuscation requested in https://github.com/realm/realm-object-store/issues/680 (but will make development a bit harder because you don't know which file to look at anymore).

**Comment by it2lars** [comment]
We're running into the same issue:

`Realms.Exceptions.RealmFileAccessErrorException: 'Unable to open a realm at path 'C:\Users\roessigerla.IT2MBIZZ\AppData\Local\Packages\IT2mediaGmbHundCo.KG.SalesNetwork_cjxn3p1bw7mtm\LocalState\realm-object-server\0832ed08-9d8c-4d50-b42d-65a6fa321615\realms%3A%2F%2Fsnwx-dev.de1a.cloud.realm.io%3A443%2FOrganizationTest1.management': make_dir() failed: No such file or directory Path:.'`

Is there any workaround? Setting LongPathsEnabled in the Windows Registry to 1 doesn't help.

**Comment by lordasgart** [comment]
Same problem here with Xamarin and UWP!

And you do not have really much options:

- Force the user to change the username?
- Change your company name of your already published store app?
- Only name your realms A/B/C in future... ?

**Comment by ThomasKison** [comment]
This problem is really annoying. Can you please support us with an appropriate solution for that? We already renamed all our instances with shorter names, but as soon as someone with a long name uses our app, it will crash.

**Comment by mediasven** [comment]
We have the same problem here (Xamarin and UWP). 
We have already renamed the instance names. However, we have no control over the usernames. For users with a longer name, the app crashes.

**Comment by lordasgart** [comment]
Suggestion:

realms://appname-env.de1a.cloud.realm.io:443/~/MyTooLongTestRealm.management

**Instead of escaping this way:**
realms%3A%2F%2Fappname-env.de1a.cloud.realm.io%3A443%2F%7E%2FMyTooLongTestRealm.management

Omit all url specific characters:
realmsappname-env.de1a.cloud.realm.io443%7EMyTooLongTestRealm.management

And if we do not need the scheme "realm":
appname-env.de1a.cloud.realm.io443%7EMyTooLongTestRealm.management

Maybe this could be only enabled via configuration, so anyone who needs this can opt in for this new behaviour!
