### ISSUE TITLE
Open Realm with server-side history

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-object-store#687]
When opening a Realm copied from ROS as a local file Realm JS throws an error:

> Incompatible histories. Expected an empty Realm or a Realm written by Realm Mobile Platform.

See https://github.com/realm/realm-studio/issues/870 for context and a screenshot of this.

In its current form, I can use Realm JS to open a file with a client-side history by providing `{ ..., sync: true, ... }` in the config object passed to the Realm constructor, but there is no way of opening a Realm with a server-side history.

**Comment by roberhofer** [comment]
Internal AHA reference: https://realmio.aha.io/features/ROS-93
