### ISSUE TITLE
Realm write transaction should have optional diff of overwritten object

### ISSUE THREAD

**Issue by roberhofer** [realm/realm-object-store#697]
As a mobile app developer, it is a common practice to create an unmanaged object of a particular view and then once the user is done with the view - turn the unmanaged object into a managed realm object - and commit the transaction to Realm by overwriting the existing realm object in the realm.

 

For sync, this creates a plethora of unnecessary SET transactions for fields that have not changed and clogs up the operation log on the backend - leading to all sorts of unintended side affects (poor merging and seeks).

 

Instead an optional parameter should be allowed for the developer to diffOrUpdate which only updates the fields that have changed  
  
  
See this ticket and real-world example:  
https://realm.freshdesk.com/helpdesk/tickets/1741

Aha! Link: https://realmio.aha.io/features/ROS-119

**Comment by roberhofer** [comment]
@bmunkholm : Can you identify who from the core/object team can focus on this in the upcoming Sprint?

**Comment by ironage** [comment]
This topic has been raised before and typically implemented at the binding level, see [this comment](https://github.com/realm/realm-object-store/issues/661#issuecomment-396878968) for why it hasn't been implemented at a lower level yet. I'm not against the change, but want to show there are reasons why we haven't done this yet.

**Comment by bmunkholm** [comment]
@jedelbo ^

**Comment by astigsen** [comment]
> This topic has been raised before and typically implemented at the binding level, see this comment for why it hasn't been implemented at a lower level yet.

The goal is to implement it as an optional feature on the `createOrUpdate` method. In this way it is something done explicitly by the developer. If their intended merge behaviour depends on all changes being reported, they can choose to not use this feature.

**Comment by jedelbo** [comment]
At the binding level you should notice that Object::create() and `unbox<class T>`has been added 2 new parameters:
- `update_only_diff` indicates if we should try to update only properties that are different from what is already in the database.
- `current_row` tells which already existing row in the database we should associate this new object with. This parameter has only relevance if `update_only_diff` is true and is particularly needed in `unbox<RowExpr>` as it is called with the same parameters. You can check `CppContext::unbox<RowExpr>` for reference (https://github.com/realm/realm-object-store/blob/1f91c82eb34cf4eaa2900794a9268390876f19f1/src/impl/object_accessor_impl.hpp#L180)
@cmelchior you should be aware of the `current_row`parameter.

**Comment by bmunkholm** [comment]
Create issues in each repo of the remaining SDKs.

**Comment by bmunkholm** [comment]
Issues for other SDK's has been created.

**Comment by bmunkholm** [comment]
Closing as we only need to merge Cocoa now.
