### ISSUE TITLE
Add asyncOpen timeout to client sdk

### ISSUE THREAD

**Issue by ianpward** [realm/realm-object-store#768]
Currently when a client sdk does an asyncOpen the code will hang until the realm is fully downloaded. If the mobile device is offline or for some other reason like ROS is slow or unavailable the whole app gets blocked (since a realm reference is not returned). If we could add an optional timeout parameter this would enable customers to better troubleshoot their apps

**Comment by nirinchev** [comment]
Wouldn't that be easily implemented at the SDK level? E.g. in js we could do a `Promise.race` with a timeout promise, etc. But I believe we need a more precise requirements to do a proper estimate.

**Comment by bmunkholm** [comment]
Java supports this already. 
Needed for JS, Cocoa, and .Net eventually.
