### ISSUE TITLE
Where is <realm/sync/client.hpp> ?

### ISSUE THREAD

**Issue by njlr** [realm/realm-object-store#772]
I get this compilation error: 

> realm-object-store/src/sync/sync_manager.hpp:26:10: fatal error: 'realm/sync/client.hpp' file not found
#include <realm/sync/client.hpp>

I know that I can fetch this header using `build.sh download-sync`. However, I want to build from source, and that script fetches prebuilt libraries. Where can I find the Git repo containing this header? 

Where is `realm/sync/client.hpp`?

**Comment by tgoyne** [comment]
The sync library is not open source, and is only available in binary form.
