### ISSUE TITLE
Update query held by Results (and enable fine-grained notifications for the change)

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-object-store#777]
When doing incremental updates to query, e.g. filtering a list it would be useful if you could re-use the existing `Results` class, but just update the underlying query.  The reason behind is that this should enable fine-grained notifications (and thus nicer UI animations) for an increasingly refined query. 

This has been brought up as a use here: https://github.com/realm/realm-java/issues/6216 and for Subscriptions here: https://github.com/realm/realm-object-store/issues/767#issuecomment-461031678

The public API should be relatively simple, something like `Results::update_query(TableView)`` or `Results::update_query(Query)`, but the bulk of the work probably has to be in the notification system.

**Comment by bmunkholm** [comment]
Moved to https://github.com/realm/realm-core/issues/4609
