### ISSUE TITLE
Support for field aliases

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-object-store#780]
In order to implement https://github.com/realm/realm-js/issues/2266 we need to support field aliases in order to avoid breaking changes.

This should be relatively simple by extending the Property class with this. 

TODO
- [ ] Add support to `Property`
- [ ] Validating a schema should ensure that an alias doesn't conflict with an existing property name.

**Comment by ironage** [comment]
Can you give an example of what you mean by alias?
The query parser supports property aliasing already and is using it to transform user names of linkingObjects properties into a version that the parser understands (eg: `@links.class_From.forward_link`). Is this the same thing you need?

**Comment by cmelchior** [comment]
Fixed by https://github.com/realm/realm-object-store/pull/783
