### ISSUE TITLE
Core6: nullability checks for list of primitives

### ISSUE THREAD

**Issue by nhachicha** [realm/realm-object-store#822]
Core6 allows inserting null value for a list of primitives of non-nullable types 
Reproduction case
```C++
            InMemoryTestFile config;
            config.automatic_change_notifications = false;
            config.schema = Schema{
                {"AllTypes", {
                    {"bool array", PropertyType::Array|PropertyType::Bool},
                }}
            };
            config.schema_version = 0;
            auto realm = Realm::get_shared_realm(config);
            auto table = realm->read_group().get_table("class_AllTypes");

            CppContext ctx(realm);
            AnyDict value {{"bool array", AnyVec{true, false}},};
            realm->begin_transaction();
            auto obj = Object::create(ctx, realm, *realm->schema().find("AllTypes"), util::Any(value), false);

            auto list = any_cast<List>(obj.get_property_value<util::Any>(ctx, "bool array"));
            util::Optional<bool> newValue = util::none;
            list.add(newValue); // <--- this should crash 
            realm->cancel_transaction();

```

The above test will crash as expected in Core5 
```
 Attempted to insert null into a non-nullable column
```
However, this passes correctly in Core6.

I think this happens because in Core5 because adding a new element end up invoking `m_table->set(0, m_table->add_empty_row(), value);` in https://github.com/realm/realm-object-store/blob/bec15175287165322088b682032d14e6dbaa813c/src/list.cpp#L213-L217 which performs the nullability checks and throws, However in Core6 this is using `as<T>().add(value);` in https://github.com/realm/realm-object-store/blob/core-6/src/list.cpp#L205-L210 which deosn't perform any nullability checks to my knowledge.

**Comment by jedelbo** [comment]
Issue moved to [realm/realm-core-private #327](https://github.com/realm/realm-core-private/issues/327) via [**ZenHub**](https://www.zenhub.com/)
