### ISSUE TITLE
Debug assertion in Windows debug build

### ISSUE THREAD

**Issue by blagoev** [realm/realm-object-store#832]
We have this test in https://github.com/realm/realm-js/blob/a4c0c8f81d80edc6e78102bb8cd6dd2a52622a91/tests/js/list-tests.js#L111 which in Windows debug builds asserts with the following message

Expression: can't dereference out of range vector iterator

Here is a short version of this test which also reproduces the problem
```
testListSubscriptGetters: function() {
        const realm = new Realm({schema: [schemas.LinkTypes, schemas.TestObject, schemas.PrimitiveArrays]});
        let obj, prim;

        realm.write(() => {
            prim = realm.create('PrimitiveArrays', {
                 int:    [1, 2]
            });
        });
    },
```

It seems when realmjs searches for a schema name which does not exists. The Schema::find(StringData name) method returns the it = end() which when dereferenced later causes the debug assertion

https://github.com/realm/realm-object-store/blob/master/src/schema.cpp#L53-L62

**Comment by jedelbo** [comment]
I think the problem lies with the realm-js Context implementation. You should only try to find the schema if the property has type `PropertyType::Object`.

**Comment by blagoev** [comment]
a possible fix for this is here: https://github.com/realm/realm-js/pull/2579
