### ISSUE TITLE
Core6 equalTo not working on 32bit architectures 

### ISSUE THREAD

**Issue by nhachicha** [realm/realm-object-store#841]
Using the `equalTo` predicate is not working (using greater than works) on 32bit platform x86/armeabi-v7a
Here's a test that exposes this behaviour.

- Install Virtual Box
- Download a 32bit Linux image (example https://sourceforge.net/projects/osboxes/files/v/vb/55-U-u/16.04/16.04.6/1604.632.7z/download)
- Create a new Virtual Box 32 bit Linux image & import the downloaded VDI (https://blogs.oracle.com/oswald/importing-a-vdi-in-virtualbox)
- install the following dependencies to be able to compile OS/Core & Sync 
```
apt-get install -y wget build-essential lcov curl cmake gcovr libssl-dev git python-cheetah libuv1-dev ninja-build adb xutils-dev libprocps-dev
```
- You need to compile the recent version of Cmake from source since the binaries are not available for 32bit platform 
```
wget https://github.com/Kitware/CMake/releases/download/v3.15.3/cmake-3.15.3.tar.gz
tar xvf cmake-3.15.3.tar.gz
cd cmake-3.15.3
  ./bootstrap
  make
  make install
```
- Now pull Core/Sync & OS dependencies & compile using 
```
cmake -DREALM_ENABLE_SYNC=1 -DREALM_CORE_PREFIX=/path/to/realm-core -DREALM_SYNC_PREFIX=/path/to/realm-sync
```
- Add the following test to `schema.cpp` for example 
```C++
SECTION("EQUALTO_ISSUE") {
     Realm::Config config;
    config.path = "/tmp/test99.realm";
    config.schema =  Schema{
            {"StringClass", {
                                 {"name",PropertyType::String|PropertyType::Nullable, Property::IsPrimary{true}},
                         }}
    };
    config.schema_version = 0;
    auto realm = Realm::get_shared_realm(std::move(config));

    auto table = realm->read_group().get_table("class_StringClass");

    std::cout << "TABLE SIZE Before: "<< table->size() << std::endl;// SEE OUTPUT1

    realm->begin_transaction();
    auto obj = sync::create_object_with_primary_key(static_cast<Transaction&>(realm->read_group()), *table, realm::StringData("Foo"));
    const Table& t = *(table);
    Query* query = new Query(table->where());
    size_t count = query->equal(table->get_column_key("name"), "Foo", true).count();

    std::cout << "QUERY COUNT: " << count << std::endl;// SEE OUTPUT2
    std::cout << "TABLE SIZE After " << table->size() << std::endl;// SEE OUTPUT3

    StringData d = table->begin()->get<StringData>("name");
    std::cout << "TABLE first elem " << d.data() <<std::endl;// SEE OUTPUT4

    realm->commit_transaction();
    realm->close();
        }
```

| OUTPUT | 64 Arch (x86_64/arm64)  | 32 Arch (x86/armeabi-v7a) |
| --------- | -------------------------- | --------------------------- |
| OUTPUT1 | 0  | 0  |
| OUTPUT2 | 1  | 0  |
| OUTPUT3 | 1  | 1  |
| OUTPUT4 | Foo  | Foo  |

_Note_ I had to exclude `tests/sync/partial_sync.cpp` from the test suite since it was not completing sometimes on 32bit (irrelevant to this issue)

**Comment by jedelbo** [comment]
I can now reproduce the problem.

**Comment by jedelbo** [comment]
Issue moved to [realm/realm-core-private #330](https://github.com/realm/realm-core-private/issues/330) via [**ZenHub**](https://www.zenhub.com/)
