### ISSUE TITLE
Don't bleed non-idiomatic terminology into SDKs

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-object-store#886]
Errors thrown when opening a Realm (using Realm JS) with an invalid schema contains types and terminology which is not used anywhere in the RealmJS documentation.

For example, when accidentally defining a schema with a **list** with **optional** elements of some object type:

```javascript
const Realm = require("realm");
new Realm({
  schema: [{
    name: "SomeClass",
    properties: {
      someList: { type: "list", objectType: "SomeClass", optional: true },
    },
  }],
});
```

The following error [is thrown](
https://github.com/realm/realm-object-store/blob/master/src/object_schema.cpp#L167):

```
Error: Schema validation failed due to the following errors:
- Property 'SomeClass.someList' of type 'array' cannot be nullable.
```

It uses words like "array" and "nullable", which is not a part of the Realm JS terminology. This is potentially very confusing for a newcomer trying to write a schemas and getting errors in the process.

I created this issue on the realm-object-store repository because I believe it should support some sort of mapping of these terms on a per-SDK level. An alternative solution would be to check for these conditions in Realm JS, before parsing a potentially invalid schema to object store, but that duplicates logic across multiple code-bases and that also didn't seem ideal.

**Comment by bmunkholm** [comment]
Perhaps a callback to the SDK to provide the error could be a solution if configuration of the error message is tricky.

**Comment by cmelchior** [comment]
This is also a problem in Java where the word `property` is a bit misleading as well. It is tricky to fix though without adding a ton of extra complexity to how exceptions are thrown.

**Comment by bmunkholm** [comment]
Moved to https://github.com/realm/realm-core/issues/4191

**Comment by bmunkholm** [comment]
ignore this.
