### ISSUE TITLE
gitmodule url update

### ISSUE THREAD

**Issue by kostagr33k** [realm/realm-object-store#909]
I am working to use AWS codepipeline but unfortunately the url used in the external/catch submodule needs to have .git appended to the url as AWS has troubles sometimes with submodule urls that do not end in .git . Following link has some explanation 
[https://stackoverflow.com/questions/53785769/aws-codebuild-error-on-download-source-client-error-repository-not-found-for-p](url)

file: realm-object-store/.gitmodules

From:

[submodule "external/catch"]
        path = external/catch
        url = https://github.com/catchorg/Catch2

To

[submodule "external/catch"]
        path = external/catch
        url = https://github.com/catchorg/Catch2.git

**Comment by bmunkholm** [comment]
Seems like something you could make a PR for perhaps? @kostagr33k

**Comment by bmunkholm** [comment]
Moved to https://github.com/realm/realm-core/issues/4608
